### ISSUE TITLE
Forward slashes not recognized anymore

### ISSUE THREAD

**Issue by pablogipi** [chrisant996/clink#113] opened 2021-05-10 02:50 UTC
Hello.
Just update cmder which is using this latest clink version and I found that forward slashes are not recognized anymore.
In clink 0.4.9 forward slashes were automatically translated to backward slashes, and even better using clink.slash_translation() from the Lua API one can setup clink to use forward slashes like in an UNIX shell.

Is there any reason because in the new versions of clink the forward slash translation has disappeared along with clink.slash_translation() removed from the LUA API?

Thanks for the excellent work with clink!

**Comment by chrisant996** [comment] 2021-05-10 16:25
Please share specific examples.

When I type `echo /windows/sys`<kbd>Tab</kbd> it autocompletes to `echo \Windows\Sys`.

**Comment by pablogipi** [comment] 2021-05-11 10:11
Hey chrisant996.
I was using the latest cmder, I think is 1.3.18, in fact I have to fallback to 1.3.16 which uses clink 0.4.9 because of this issue.
Now, whether the problem is coming from clink or something in cmder, that is something I'm not sure to be honest.
cmder 1.3.18 is using clink 1.1.45 (https://github.com/cmderdev/cmder/releases)

Thanks for adding `clink.slash_translation()`, auto translate of forward slashes to backslashes is useful, but for me being able to use forward slashes transparently is much better, and that function allows that.

**Comment by chrisant996** [comment] 2021-05-11 14:45
@pablogipi It would help me to help you, if you could answer the questions I asked.

In the meantime, I will assume that the problem was actually reported backwards by mistake -- I.e. Clink translates slashes to backslashes just fine, and that translating backslashes to slashes is what was desired.

I will publish a new release with the changes, and I just won't be able to verify in advance whether it solves the reported issue since there are no specific examples for me to test.  At this point I'm pretty sure that I've understood the issue correctly, even though my understanding is opposite from the statements in the original report.

**Comment by pablogipi** [comment] 2021-05-11 16:13
Sorry chrisant996, but I always have used clink with cmder.
So I tried just starting clink from the version included in cmder using the clink.bat script and in the clink terminal all works as expected.
The only issue then was only the missing API calls that you are going to add.
Sorry for the confusion and thanks!

**Comment by chrisant996** [comment] 2021-05-11 18:26
They do fairly regularly.

In the meantime you can copy Clink in to the `vendor\clink` directory of Cmder.

**Comment by pablogipi** [comment] 2021-05-12 09:18
Thanks chrisant996, I'll do.

I'll try to be more specific with examples next time.

**Comment by pablogipi** [comment] 2021-05-18 02:12
Hello chrisant996.
I have been testing version 1.2.7, and seems that path completions only works wit backslashes?
So lets say I have a folder `C:\dev\proj1`
I type: `cd \dev\p` then press `TAB` and it correctly autocomplete proj1. This is using `match.translate_slashes` set to __system__ (the default)
Now I change `match.translate_slashes` set to __slash__ and when I press `TAB` it converts backslashes to forward slashes as expected but it **cant** autocomplete the rest of the path as expected.

I have also test the Lua API and now I don't get errors when trying to use `clink.slash_translation()`, but I cant get paths matching working.
I have commented the code I used for 0.4.9 which is now deprecated and I have a file called cmder.la in my config with the next code, from the help:
```
local force_slashes = clink.generator(-1)
function force_slashes:generate()
  clink.translateslashes(2)    -- Convert to slashes.
  return false                 -- Allow generators to continue.
end
```
The behavior is really strange. So Im at  my %userpfofile%, and then type `cd AppD` press `TAB`, and it autocomplete to `cd AppData\`
Look how is not converting to forward slash. Once complete then I press `TAB` again, and now it converts the bac slash into forward slash. So I have to press `TAB` twice.
Anothe strange thing, in this case I want to jump to a folder in `C:\dev`, so I type `C:de` and press `TAB` and it doesn't complete to `C:/dev`

I have recorded a screen session to show the issues: https://www.loom.com/share/c849c6e405f34f6d8d0c40565923421e

Thanks

**Comment by chrisant996** [comment] 2021-05-18 03:51
This interesting, and thank you very much for the detailed example and information!

There are a few things going on.

First of all, slash is a flag character in Windows, and the `cd` argmatcher knows about the `cd` command's `/d` flag.  So yeah, forward slash ends up not working because it gets interpreted as a flag instead of a path.

Second, CMD's `cd` command has a special quirk:  it recognizes exactly and only `/d` as a flag.  If you use `cd /foo` it will change to the /foo directory.  But if you use `cd /d /foo` it fails because now it knows that the caller knows the difference between a flag character and a path separator, and the /foo is not a valid path.  So it only accepts *nix style paths in certain cases.

Third, there are a LOT of program on Windows that will not work with paths that use forward slashes.  I guess that this old slash translation feature of Clink was intended for use by people who exclusively use cygwin programs and/or native WSL programs, but for some reason don't want to use bash?

This is going to be very expensive for me to try to produce at best only _partial_ functionality, by introducing hacks in many places, with special edge case handling, and trying to predict how to "safely" interfere with other programs and scripts.

Can you help me understand the specific intended benefits of the slash translation feature?  If the only benefit is to not have to type a backslash instead of a tab, then I'm not sure this is really worth trying to support.  What are other benefits?

**Comment by chrisant996** [comment] 2021-05-18 16:56
It turned out this was much simpler than it looked:

> I have been testing version 1.2.7, and seems that path completions only works wit backslashes?

I noticed the testing was focused on only one command:  `cd`.

That command has a `/d` flag -- Clink 1.x knows about the `/d` flag but Clink 0.4.9 doesn't know about that flag.  That's why Clink 0.4.9 works for completing `cd /jobs/` and etc.  Since it doesn't know about any flags, it doesn't interpret `/jobs` as a flag.

Fixed for v1.2.8 (later this week).  I've made Clink v1.2.8 turn off recognizing `/` as a flag character when slash translation is set to forward slashes.  Of course that will break completing flags for some commands' argmatchers, but it will allow completing directories that start with a path separator.  It also fixes a problem that Clink 0.4.9 had with slash translation in commands whose argmatchers listed any flags using forward slash.

> The behavior is really strange. So Im at my %userpfofile%, and then type `cd AppD` press `TAB`, and it autocomplete to `cd AppData\`

This is because my slash translation implementation neglected to account for directories marked as readonly.  Some directories under %USERPROFILE% are marked readonly, and those ones didn't get slash translation performed on them.

Fixed for v1.2.8 (later this week).

> Anothe strange thing, in this case I want to jump to a folder in `C:\dev`, so I type `C:de` and press `TAB` and it doesn't complete to `C:/dev`

Is the `C:de` a typo?  `cd c:de` would not complete to `cd c:/dev`, but **_if_** the current working directory is c:\ then it could complete to `c:dev/`.  This is how Windows relative paths work and is also how Clink 0.4.9 works, and it seems to be working correctly for me with Clink v1.2.7 as well.

**Closed** 2021-05-18 17:05 UTC

**Comment by pablogipi** [comment] 2021-05-19 02:07
Hello chrisant996.
Thanks a lot for the changes.
For turning off recognizing `/d` in `cd`, this is something that is probably better as an option?
The fix about detecting directories marked as readonly, is this also affecting symlinks?. In the video I sent showing my issues, there is part dedicated to `ls`. You can see how the old clink can autocomplete after looking into /jobs, where as the latest clink cant. What happens is that after completing /jobs/ it is not to continuing completing or giving options for the elements under my current fir.
I'll double check the last point.
Thanks!

**Comment by chrisant996** [comment] 2021-05-19 02:30
> For turning off recognizing `/d` in `cd`, this is something that is probably better as an option?

Why?  The auto-disabling will _**only**_ affect users who force slash translation to use forward slashes.

The problem is bigger than just `/d` in `cd`.  It affects _**all**_ argmatchers that define any forward slash flags.  Any of those will be unable to complete `/some_dir` properly unless forward slash is disabled as a flag character while slash translation is set to use forward slashes.  That's why it needs to auto-disable.  There is a much broader problem than just with `cd`.

> The fix about detecting directories marked as readonly, is this also affecting symlinks?

If they are for directories and are readonly, sure.  It has nothing to do with symlinks, but of course a symlink can be a readonly directory.  But the symptom of that problem is that backslashes show up; that's all.

> In the video I sent showing my issues, there is part dedicated to `ls`. You can see how the old clink can autocomplete after looking into /jobs, where as the latest clink cant. What happens is that after completing /jobs/ it is not to continuing completing or giving options for the elements under my current fir.

No, that has nothing to do with `ls`.  You're not doing any autocompletion after `ls` -- in the video you just press <kbd>Enter</kbd> after `ls`.

You're only ever doing completions after `cd`.

The `cd /jobs/` issue is exactly the issue I discussed above.

**Comment by pablogipi** [comment] 2021-05-19 09:47
Cool, thanks chrisant996.
I'll give it a go to v1.2.8 as soon as is released.
Thanks!

**Comment by pablogipi** [comment] 2021-06-03 11:46
Hello chrisant996.
I have been using v1.2.9 an overall everything is working fine. Never used the complete popup menu, is nice.
There are still some inconsistencies about using slashes instead of backward slashes, I'm sure you are aware of them and some 
has been discussed here before, but I want to share a screenshot to shows some of them to see if there is something that can be done in clink to alleviate these issues:
![image](https://user-images.githubusercontent.com/69514972/120638229-6592f880-c45f-11eb-8244-ce44ea51515a.png)

As you can see commands in many cases doesn't play well when using  slashes, I don't know if there is any way clink can translates these slashes into backward slashes? It seems to be doing it well with `cd`, is that the only command supported?
I was assuming clink was translating all slashes into backward slashes and passing them to CMD, so basically CMD only see backward slashes but the user uses forward slashes. I know this can invalidate arguments in windows commands that usually use forward slashes to indicate argument.
Is strange because the forward slash trick seems to work when I'm working on paths on the same disk but at the moment is involves paths that have symlinks I have to sue backward slashes:
![image](https://user-images.githubusercontent.com/69514972/120639439-db4b9400-c460-11eb-9878-024dfaa714ca.png)

As you can see in my system \mnt\test21019 is a symlink, if I want to copy something using `cp` to it from my local disk I have to use backward slashes, using forward fails.
I think this issue is what is causing some of the inconsistencies using slahes in our systems since we use symlink quite often.

Thanks

**Comment by chrisant996** [comment] 2021-06-03 15:18
Does v0.4.9 behave differently?

**Comment by chrisant996** [comment] 2021-06-03 19:24
If someone wants to use Linux on Windows, would bash not be a more natural choice than CMD+Clink?

It sounds like what's desired here is quite a lot of major (and magical + inherently ambiguous) functionality changes to predict how other programs will behave and silently alter the user's input. But Clink is not about trying to make CMD not be CMD or not be Windows -- it's just about enhancing the input experience.

**Comment by pablogipi** [comment] 2021-06-04 12:03
Yeah I understand is not an easy thing, is interesting that Microsoft accepted forward slashes as separators time ago but never  wanted to make the move and forget about backward slashes.
Bash on windows doesn't come without caveats, you end up with a subsystem inside your OS, you can use git for windows or WSL, they are great but also have their limitations.
My question was more in the direction to know whether or not there are issues with symlinks and clink. I have had several issues on other apps because they use old APIs that doesn't work with symlinks correctly. Symlinks are more or less a new thing in the windows ecosystem and lots of tools doesn't work correctly with them, however they work great at  a OS level and most of the issues I'm detecting with the forward/backward slashes seems to be associated to paths that use symlinks under the hood.

**Comment by chrisant996** [comment] 2021-06-04 15:25
> Yeah I understand is not an easy thing, 

Ok. If you find a way to define specifically what you want, do share it.  

> Bash on windows doesn't come without caveats, you end up with a subsystem inside your OS, you can use git for windows or WSL, they are great but also have their limitations.

Of course. But if specific reasons can be shared about why, then that might help find some compromise.

For example, why does Clink have to magically read minds and correctly guess between ambiguous choices? Why can't the user help?

What if there were a key binding to convert an command line argument to slashes or backslashes? Press repeatedly to convert back and forth.

> My question was more in the direction to know whether or not there are issues with symlinks and clink. I have had several issues on other apps because they use old APIs that doesn't work with symlinks correctly. Symlinks are more or less a new thing in the windows ecosystem and lots of tools doesn't work correctly with them, however they work great at  a OS level and most of the issues I'm detecting with the forward/backward slashes seems to be associated to paths that use symlinks under the hood.

Symlinks have been around in Windows for decades.  I haven't noticed many tools behaving incorrectly, but maybe I'm not doing special edge case things, and maybe most tools work in general-case usage situations.

Can you explain specifically what issues you are encountering with symlinks and Clink?

I see an issue with `cp` in the screenshot.  But `cp` is not Clink.  How slashes or backslashes are handled by programs is defined by those programs, not by Clink.  I don't understand what is expected from Clink there.
