### ISSUE TITLE
Install from scoop : no prompt nor Ctrl+L.

### ISSUE THREAD

**Issue by j-lecrivain** [chrisant996/clink#31] opened 2020-12-14 10:57 UTC
Hi there,

I use clink everyday at work. Thanks you for reviving it !
However, since scoop updated its version to your repo, clink doesn't display the CMD prompt anymore. It happens in either injected or in autorun.
Usual commands like DIR are still working except I don't have a prompt and Ctrl+L doesn't clear the CMD anymore. It is not the most practical for daily usage.
My version is 1.1.8.f031c7, running in plain Windows 7 CMD.

Could you get a look at it ?

**Comment by chrisant996** [comment] 2020-12-17 12:53
Sorry about that, and thank you for reporting the issue.

It might have to do with changes in Clink v1.x to where it loads scripts from.
Can you try v1.1.9 and see if that resolves the issue?  It should behave closer to how v0.4.8 did.

If that doesn't resolve the issue, then can you share more information so that I can take a look?
- What and where is scoop?
- Where are your Clink scripts located?
- How can I reproduce the problem in a fresh installation?

**Comment by chrisant996** [comment] 2020-12-17 13:02
Looks like #32 includes the Clink log output, which reveals that on Windows 7 there's a problem hooking the ReadConsoleW function in kernelbase.dll.  I'll use #32 to track the problem, and close #31 as a duplicate of #32.

Thanks again for reporting the issue!  It might take a few days to figure out how to solve the issue since I don't have a Windows 7 machine available.

**Closed by chrisant996** 2020-12-17 13:02 UTC
Labels: question

**Comment by j-lecrivain** [comment] 2020-12-17 13:04
Ok, I'll keep track of the issue #32. Thank you.
