### ISSUE TITLE
Sending Keystrokes fails for some keys

### ISSUE THREAD

**Issue by 264312431** [chrisant996/clink#249] opened 2022-03-02 11:44 UTC
Hi,

some keys fail when trying to send keystrokes to a clink console window. You can reproduce it with this hybrid batch/js file. 
I think WshShell.SendKeys boils down to WM_KEYDOWN/UP messages (or at least doing so manually gives the same result)
Is there fix for this? Thanks for awesome clink anyway!!

Also maybe this is related?
https://github.com/chrisant996/clink/issues/234

### testKeys.bat:

```
@if (@CodeSection == @Batch) @then
::===============  Batch Part  ======================
@echo off
if "%~1" EQU "" (
     echo examples working with clink:
     echo testKeys "echo blahx{BACKSPACE}{ENTER}"
     echo testKeys "^{ESCAPE}"
     echo not working:
     echo testKeys "bleh{LEFT}{LEFT}{DELETE}a{RIGHT}"
     goto :EOF
 )
cscript //nologo //E:JScript "%~F0" %*
goto :EOF
//=============== JScript Part ======================
@end
var WshShell = WScript.CreateObject("WScript.Shell");
WshShell.SendKeys(WScript.Arguments(0));
WshShell.Quit;

```

**Comment by chrisant996** [comment] 2022-03-02 17:15
It's because WScript is sending 0 for the key scan code.
It is not accurately/properly sending the keys.

Clink's keyboard driver uses the key scan code, for some keys.  I wouldn't have used the scan code here, but there might be some kind of special case Martin was trying to solve by using the scan code.

I can try using only the virtual key code (which is the only thing WScript is sending).  I would expect that will still work properly, but I don't what problems Martin was trying to solve by using the scan code, so it might break something else.  If it does break something else, then I may have to go back to using scan codes.  We will see!

You're right, there is potential that #234 is this same issue.  But I am able to reproduce the WScript issue, and I am not able to reproduce the virtual keyboard issue -- for me, the virtual keyboard sends the correct scan code for the keys.

----
When I enable debug verbose input tracing, it shows the following:
```
c:\chrisant>key event:  ___ __  flags=0x00000000  char=0x0062  vk=0x0042  scan=0x0000  "B"
bkey event:  ___ __  flags=0x00000000  char=0x006c  vk=0x004c  scan=0x0000  "L"
lkey event:  ___ __  flags=0x00000000  char=0x0065  vk=0x0045  scan=0x0000  "E"
ekey event:  ___ __  flags=0x00000000  char=0x0068  vk=0x0048  scan=0x0000  "H"
hkey event:  ___ __  flags=0x00000000  char=0x0000  vk=0x0025  scan=0x0000  "Num 4"
key event:  ___ __  flags=0x00000000  char=0x0000  vk=0x0025  scan=0x0000  "Num 4"
key event:  ___ __  flags=0x00000000  char=0x0000  vk=0x002e  scan=0x0000  "Num Del"
key event:  ___ __  flags=0x00000000  char=0x0061  vk=0x0041  scan=0x0000  "A"
akey event:  ___ __  flags=0x00000000  char=0x0000  vk=0x0027  scan=0x0000  "Num 6"
mouse event:  0,66  ___ __  ctrlkeystate=0x00000000  buttonstate=0x0002  eventflags=0x0000
```

You can see the scan code is 0 for everything.  That's not normal behavior.

The name "Num 4" is coming from the OS -- that is the name the OS has for the `VK_LEFT` key, even though it is actually the <kbd>Left</kbd> key and not the <kbd>Numpad 4</kbd> key.  That part is weird, but is the normal behavior.  Again, if the scan code were provided, then that is what would enable finding the correct name for the key.

**Comment by 264312431** [comment] 2022-03-02 19:58
yeah, it gets the name based on the scancode only (and left and num4 share the same scancode) 

with hw keyboard:
VK_LEFT 
key event:  ___ __  flags=0x00000120  char=0x0000  vk=0x0025  scan=0x004b  "4 (ZEHNERTASTAT"
VK_NUMPAD4 
key event:  ___ __  flags=0x00000020  char=0x0034  vk=0x0064  scan=0x004b  "4 (ZEHNERTASTAT"

so i guess for the special case of scancode == 0 you could just call MapVirtualKey and fill it?

**Comment by chrisant996** [comment] 2022-03-02 20:32
> yeah, it gets the name based on the scancode only (and left and num4 share the same scancode) 
> 
> with hw keyboard:
> VK_LEFT 
> key event:  ___ __  flags=0x00000120  char=0x0000  vk=0x0025  scan=0x004b  "4 (ZEHNERTASTAT"
> VK_NUMPAD4 
> key event:  ___ __  flags=0x00000020  char=0x0034  vk=0x0064  scan=0x004b  "4 (ZEHNERTASTAT"
> 
> so i guess for the special case of scancode == 0 you could just call MapVirtualKey and fill it?
> 

Scan code is supposed to be the physical key identifier.  I thought that the physical Left key and the NumLock-Off-NumPad4 form of "Left" would have different scan codes. But they have the same, and it's the FLAG_EXTENDED flag that differentiates between them.  It's been too long since I wrote a keyboard driver, and I forgot some of the details.

(Clink does fetch the scan code from the vk, when getting a key name.  But I had thought it might get a more accurate key name if the scan code from the actual input were used.  But of course it won't, because of how FLAG_EXTENDED works.)

As best I could determine from source history and comments, the original use of scan code was due to a misunderstanding, and wasn't solving a problem.  So, I think the fix should work well and be unlikely to cause problems.

If you build Clink from the repo, the fix is present.  Or I expect to publish a new release sometime this week or weekend.

**Comment by 264312431** [comment] 2022-03-02 20:34
like in win_terminal_in.cpp..
```
    // Convert enhanced keys to normal mode xterm compatible escape sequences.
    if (key_flags & ENHANCED_KEY)
    {
 		// fix for applications that simulate keystrokes without providing a scancode 
 		if (!key_sc) {
			key_sc = MapVirtualKeyW(key_vk, MAPVK_VK_TO_VSC);
		}
```
that seems to do it. 
appearently it's only ever used to convert enhanced keys to xterm, so i would not expect any side effects

**Comment by 264312431** [comment] 2022-03-02 20:36
ah ok :)

**Comment by chrisant996** [comment] 2022-03-03 03:27
Fixed by https://github.com/chrisant996/clink/commit/ae09d3ddb359be5d238a2605daa01d26b801ff51.

**Closed** 2022-03-03 03:27 UTC
Labels: bug
