### ISSUE TITLE
how to remove the default headers?

### ISSUE THREAD

**Issue by i2sage** [chrisant996/clink#538] opened 2023-12-13 16:20 UTC
![image](https://github.com/chrisant996/clink/assets/137275372/9b713044-1b06-489a-8fc2-3825ea1c118b)
i new to this terminal thing and specially clink and been trying to remove the default headers from yesterday, could u tell or point to a doc on how to remove it. 
version: 1.6.0

**Comment by chrisant996** [comment] 2023-12-13 18:18
Duplicate of #264.

**Closed** 2023-12-13 18:19 UTC
Labels: question
