### ISSUE TITLE
ERROR: Clink initilization has failed with error code: 0

### ISSUE THREAD

**Issue by JackieZheng** [chrisant996/clink#456] opened 2023-05-08 01:24 UTC

**Comment by chrisant996** [comment] 2023-05-08 02:05
You need to share (a lot) more context and information.

**Comment by chrisant996** [comment] 2023-05-08 02:33
Also, are you using Cmder? If so, the error is actually a known bug in _Cmder_, NOT a problem with Clink.

**Comment by chrisant996** [comment] 2023-05-11 06:22
Closing since insufficient information is provided, and it looks like a duplicate of a Cmder issue and is not a Clink problem at all.

**Closed by chrisant996** 2023-05-11 06:22 UTC
Labels: needs more information, external
