### ISSUE TITLE
将这个clink使用到ConEmu中，在终端输入命令时，命令太长导致覆盖。当doskey别名较多时，clink无法获取dockey别名

### ISSUE THREAD

**Issue by l0adingx** [chrisant996/clink#130] opened 2021-06-16 02:31 UTC
When this clink is used in conemu, when the terminal enters a command, the command is too long, causing it to be covered. When there are many doskey aliases, clink cannot get the dockey alias。
![image](https://user-images.githubusercontent.com/27912313/122148425-13a19800-ce8d-11eb-83f8-c8a9430bd993.png)
![image](https://user-images.githubusercontent.com/27912313/122148464-23b97780-ce8d-11eb-8e98-870e4fb037df.png)
If you don't enable the clink in conemu, the doskey alias can be displayed normally
![image](https://user-images.githubusercontent.com/27912313/122148676-7d21a680-ce8d-11eb-8a7b-91b9d15b201d.png)
![image](https://user-images.githubusercontent.com/27912313/122148986-ebfeff80-ce8d-11eb-917e-c2c7f855c0ea.png)

**Comment by chrisant996** [comment] 2021-06-16 04:17
I'm not able to reproduce either of the problems on my computers.

Are you able to reproduce the problems using Clink, but without using ConEmu?

### The `bbbbbbbbbbb` problem

That might be a font issue, or a codepage issue.  ConEmu uses a different font than the OS expects to be used.  Depending on the font being used + and the codepage being used + the text being displayed, ConEmu and the OS may have different opinions about how many characters fit on a line.  That can cause problems for bash and clink and other programs.

### The doskey aliases problem

1. What does `doskey /macros` report?  Are the doskey aliases not showing up because they aren't defined?
2. What happens if the latest version of Clink is used?  The latest is [here](https://github.com/chrisant996/clink/releases).
3. Can you share more information about the configuration of ConEmu and Clink?
  - Can you share the output from `clink set`?
  - Can you share the output from `clink info`?
  - Can you share whatever inputrc files `clink info` says exist (if any)?
  - Do you have any custom Lua scripts for Clink?

With more information, it may be possible to figure out what's happening.

**Comment by l0adingx** [comment] 2021-06-16 12:19
![image](https://user-images.githubusercontent.com/27912313/122216613-2ba20780-cedf-11eb-9322-134012ba33f6.png)
![image](https://user-images.githubusercontent.com/27912313/122216690-3bb9e700-cedf-11eb-88ad-23c18c25cda0.png)
As in the case above, clink cannot open the alias with the tab key.I have used the latest version of clink(1.2.13).
If I use clink version 0.4.9, it works：
![image](https://user-images.githubusercontent.com/27912313/122217536-1679a880-cee0-11eb-9a92-e58f5359ccb3.png)
![image](https://user-images.githubusercontent.com/27912313/122217651-2ee9c300-cee0-11eb-8852-9e2d8c13638d.png)

**Comment by l0adingx** [comment] 2021-06-16 12:28
The 0.4.9 version of clink can work normally in the conemu environment, but the 1.2.13 version of clink can't work normally in the conemu environment, which will cause the command can't wrap and result in string overlay.

**Comment by chrisant996** [comment] 2021-06-16 15:48
### Re: doskey aliases --

Thank you for reporting this, and thank you for giving more information.  I made a macro file with a total size of 26574 characters, and then I was able to reproduce the problem:

In commit 99b2b6566ab59a691ea4b501c4ea0adfedb14f17 I had fixed Clink to get aliases using Unicode, but I didn't notice that the optimized string class Clink uses doesn't support large strings (it is intentional that it does not; it's part of the optimization).

I've fixed the problem and will publish an updated build in the next few days.

### Re: "command can't wrap and result in string overlay" --

I see the screen shots, but they don't help me understand what steps I need to do.
Please describe the specific steps I must follow to experience the problem.

![image](https://user-images.githubusercontent.com/17440311/122251781-aaffee80-ce7f-11eb-92d9-33aa6bc1fae0.png)

Thanks!

**Comment by l0adingx** [comment] 2021-06-17 14:52
I found a new problem.First, set the CMD terminal to maximize.Then type AAAA.
![image](https://user-images.githubusercontent.com/27912313/122420087-f9b3a280-cfbd-11eb-92ab-44d681931fb4.png)
And then shrink the CMD terminal.
![image](https://user-images.githubusercontent.com/27912313/122420312-2bc50480-cfbe-11eb-9493-eb0a8dc5af19.png)
Then set the CMD terminal to maximize.
![image](https://user-images.githubusercontent.com/27912313/122420474-4c8d5a00-cfbe-11eb-9cfd-dd2c62529b82.png)
Continue to enter AAA
![image](https://user-images.githubusercontent.com/27912313/122420703-75adea80-cfbe-11eb-8652-f6a15c92e4a6.png)
The input instruction address of the CMD terminal is blank.I think this may be one of the conditions for command coverage

**Comment by chrisant996** [comment] 2021-06-17 15:45
Yes, it's a known issue that resizing the width of the terminal can mess up the input line display:
> - Changing terminal width makes 0.4.8 slowly "walk up the screen".  Changing terminal width works in master, except when the cursor position itself is affected.
(Most known issues are listed somewhere in the [todo.md](https://github.com/chrisant996/clink/blob/master/TODO.md) file.)

I haven't worked on that yet (it's very difficult to fix, because of how the operating system behaves when resizing a terminal window.)

Are you saying that the original `bbbbbbbbbbbbbbbbbbbbbbbbb` issue involved resizing the terminal window?

**Comment by l0adingx** [comment] 2021-06-17 16:04
I can't reproduce the problem of command line overlay in the CMD terminal, only in the cmder framework.

**Comment by chrisant996** [comment] 2021-06-17 17:08
> The link of 0.4.9 does not have the problem that adjusting the window size will affect the input in CMD.

0.4.9 definitely has major problems when adjusting the window size.  To observe some of the problems, maybe try more resizing operations, and try resizing so that the cursor position is affected by the resizing.  The input line can walks up the screen, lines above it can be overwritten, and the input line can be garbled.

> So I think if we solve the problem of adjusting the window to affect the input, then the problem of input command line being covered can be solved.

I need a direct answer:  Are you saying that the original `bbbbbbbbbbbbbbb` problem happened while resizing the terminal window?  If you are not, then it's a completely separate problem and will not be affected by trying to fix the terminal resize issues.

**Comment by chrisant996** [comment] 2021-06-17 17:18
> I can't reproduce the problem of command line overlay in the CMD terminal, only in the cmder framework.

That strongly suggests that it is indeed a font issue, as I mentioned at first.

Here are some issues where similar things have been reported in Cmder:
- https://github.com/cmderdev/cmder/issues/2533
- https://github.com/cmderdev/cmder/issues/2429
- https://github.com/cmderdev/cmder/issues/2427

If the issue only happens inside ConEmu, consider searching the ConEmu issues section to look for similar issues and potential workarounds.

**Comment by chrisant996** [comment] 2021-06-21 07:33
I found what's going wrong when resizing the terminal window:
1. In Martin's big rewrite, he hooked up resize support in 8aeaa14e109db046808fe009ad8f183f97b69704, and the conditional expression `if (prev_position.X < csbi.dwSize.X)` works on the first line of input when shrinking the terminal window. But it goes wrong on the second, third, etc lines, causing Clink to not notice accurately when it needs to fix the cursor position.
2. My fix for #77 (336addb9092917ce9881fcd8a4ab79c2b3d6184c) broke Clink's awareness of the "previous cursor position", allowing it to fall out of sync with the current reality, further exacerbating the problem.
3. Now that Clink has updated to using Readline 8.0 and higher, there is a new Readline function `rl_resize_terminal()` that can update the Readline input line display upon resizing the window. Updating Clink to call that mostly solves the problems, except that the incorrect conditional expression from point 1 (above) still causes Readline to draw on the wrong screen line(s).

I'm working on identifying a more correct expression to use. It's tricky because window resize works differently on Windows vs Linux, so Clink needs to translate the cursor position to where it would be on Linux (otherwise Readline's code goes haywire).

**Comment by chrisant996** [comment] 2021-06-22 01:52
v1.2.14 has some fixes.  Without more information I can't tell whether the prompt overwriting is related to terminal resize or not, so for now I'll close the issue.

**Closed by chrisant996** 2021-06-22 01:52 UTC
Labels: needs more information
