### ISSUE TITLE
remove-history working on F7 but not on Ctrl-R

### ISSUE THREAD

**Issue by ericsunplus** [chrisant996/clink#492] opened 2023-09-14 15:20 UTC
Hi Chris,

Recently I find the `remove-history` command works in `F7` context but not in `Ctrl-R` context.

In the doc it indicates `Ctrl-Alt-D` is `remove-history`, I tried and this key combination is not working. I then turned to `.inputrc` and set the following line
```
C-d: remove-history
```

Test again and `Ctrl-D` works in F7. But it still don't work when I use `Ctrl-R`.

I am in latest release version `v1.5.5.d4594d`

**Comment by chrisant996** [comment] 2023-09-14 20:25
If I remember rightly, Ctrl-R activates a special mode in the Readline library.  During that mode, it does not respond to configurable key bindings -- there is a small set of hard-coded keys it responds to.  Pressing any other key binding exits the search mode.  Depending on how it exits, it may or may not cooperate with other history related commands like `remove-history`.

I'll take a closer look in a few days.

**Comment by ericsunplus** [comment] 2023-09-15 02:29
Thank you Chris for the quick response and hint. A more direct way might be directly open the file (datebase) and edit on the history entry. From the wiki page I don't see where the history file locate at, also it is mentioned there is some "compression strategy" applied to this data base. So not sure the direct edit is feasible

**Comment by chrisant996** [comment] 2023-09-15 03:54
Oh, reading between the lines, I think maybe you want to delete entries with a particular substring, and the `F7` bound to `win-history-list` is cumbersome for that because it doesn't have a substring search.

Have you considered using the `clink-popup-history` command instead, which has incremental searching?

Also have you found the docs for pop-up windows in Clink?

https://chrisant996.github.io/clink/clink.html#popupwindow

**Comment by chrisant996** [comment] 2023-09-15 16:12
> Recently I find the `remove-history` command works in `F7` context but not in `Ctrl-R` context.
> 
> In the doc it indicates `Ctrl-Alt-D` is `remove-history`, I tried and this key combination is not working. I then turned to `.inputrc` and set the following line

@ericsunplus I tested it, and it works.  Can you please describe what behavior you expect?

Here's what I did:
- <kbd>Ctrl</kbd>-<kbd>R</kbd> is bound to `reverse-search-history` by default.
- I press <kbd>Ctrl</kbd>-<kbd>R</kbd> and type a string.
- I press <kbd>Ctrl</kbd>-<kbd>Alt</kbd>-<kbd>D</kbd>:
    - The found history entry is deleted from the history.
    - The history search ends.

That's how the Readline library and the `reverse-search-history` command are designed:  the reverse search history is a mode that has a few specific hard-coded keys.  Pressing any other key exits the mode.

So, can you please describe the following:
1. What is your overall goal?  What bigger operation are you trying to do overall?
2. What behavior do you expect?

Maybe you expect for certain commands to not exit search mode, so that you can press <kbd>Ctrl</kbd>-<kbd>R</kbd> and then repeatedly press <kbd>Ctrl</kbd>-<kbd>Alt</kbd>-<kbd>D</kbd> and <kbd>Ctrl</kbd>-<kbd>R</kbd> to do "maintenance" on the history list and delete multiple entries with a particular string?

My guess is that what you really want is to bind <kbd>F7</kbd> (or some key) to the `clink-popup-history` command (instead of `win-history-list`), and then you can use incremental searching and <kbd>Del</kbd> or <kbd>Ctrl</kbd>-<kbd>D</kbd> to delete entries.  More info on using popup window commands in Clink:  https://chrisant996.github.io/clink/clink.html#popupwindow.

**Comment by chrisant996** [comment] 2023-09-15 16:25
> From the wiki page I don't see where the history file locate at, 

Described in [File Locations](https://chrisant996.github.io/clink/clink.html#file-locations), listed in the table of contents.

I'll add a link to there from the Saved Command History section.  (I do not want to duplicate the same multi-paragraph explanations in multiple places in the documentation; that creates other problems.)

> also it is mentioned there is some "compression strategy" applied to this data base. 

Are you reading the documentation through a translator?  There is no mention of "compress" anywhere in the English documentation.  Maybe you mean the `history compact` command?

```plain
For performance reasons, deleting a history line marks the line as deleted without rewriting the history file. When the number of deleted lines gets too large (exceeding the max lines or 200, whichever is larger) then the history file is compacted: the file is rewritten with the deleted lines removed.

You can force the history file to be compacted regardless of the number of deleted lines by running history compact.
```

That describes how it works.  

I do not recommend directly editing the history file.  The format is intentionally not documented, and it has been modified at least 2 times so far.

You could also use the `clink history` command to list and find entries (for example by piping them into a script or tool), and use the <code>clink history delete <em>&lt;n&gt;</em></code> command to delete the <em>n</em>-th entry.

**Comment by ericsunplus** [comment] 2023-09-16 17:26
Hi @chrisant996 

> Have you considered using the `clink-popup-history` command instead, which has incremental searching?

I tried it today. Both `DEL` and `C-d` can delete the entries. (Though it is strange my default key setting for remove an entry is `C-d` instead of `C-A-d`)

> I tested it, and it works. Can you please describe what behavior you expect?

I simply want to delete an entry, like I do in `F7` or `clink-popup-history` mode. Exit or not exit the search mode is not a problem for me. But no matter I use `DEL` or `C-d` or `C-A-d` in reverse search mode, simply nothing happens. The entry don't get deleted and the reverse search mode is still active. 

> I'll add a link to there from the Saved Command History section
That will be great to add such cross link, actually I search for `history` in the wiki and try to find the file location around the search result.

> There is no mention of "compress" anywhere in the English documentation. Maybe you mean the history compact command?

I may get some misunderstanding of the following line in wiki

```
When the number of deleted lines gets too large (exceeding the max lines or 200, whichever is larger) then the history file is compacted
```

Wrongly understand the "compact" as "compression". But now I understand it is actually something like "entry uniq". Thank you for the very patient clarification for me!

**Comment by chrisant996** [comment] 2023-09-16 19:21
> I simply want to delete an entry, like I do in `F7` or `clink-popup-history` mode. Exit or not exit the search mode is not a problem for me. But no matter I use `DEL` or `C-d` or `C-A-d` in reverse search mode, simply nothing happens. The entry don't get deleted and the reverse search mode is still active. 

That's interesting. It works for me. Maybe some setting is responsible for the difference?

Would you be willing to share your `.inputrc` file and the full output from running `clink set`?

**Comment by ericsunplus** [comment] 2023-09-17 01:33
```
# .inputrc

C-f: "luafunc:cwdhistory_popup"
C-p: clink-popup-history
set completion-ignore-case On
```

```
# clink set

autosuggest.async                 True
autosuggest.enable                True
autosuggest.original_case         True
autosuggest.strategy              match_prev_cmd history completion
clink.autostart                   
clink.autoupdate                  off
clink.colorize_input              True
clink.default_bindings            bash
clink.logo                        full
clink.max_input_rows              0
clink.paste_crlf                  space
clink.path                        
clink.promptfilter                True
clink.update_interval             5
cmd.admin_title_prefix            
cmd.altf4_exits                   True
cmd.auto_answer                   off
cmd.ctrld_exits                   True
cmd.get_errorlevel                True
color.arg                         bold
color.arginfo                     sgr 38;5;172
color.argmatcher                  sgr 1;38;5;40
color.autoexpandtilde             bright cyan
color.cmd                         sgr 1;38;5;231
color.cmdredir                    sgr 38;5;172
color.cmdsep                      sgr 38;5;214
color.comment_row                 sgr 38;5;87;48;5;18
color.description                 sgr 38;5;39
color.divider_line                sgr 30;48;5;25
color.divider_line_end            sgr 38;5;25
color.divider_line_text           
color.doskey                      sgr 1;38;5;75
color.escapetilde                 bright cyan on blue
color.executable                  sgr 1;38;5;33
color.filtered                    sgr 38;5;231
color.flag                        sgr 38;5;117
color.git.star                    bright green
color.hidden                      sgr 38;5;160
color.histexpand                  sgr 97;48;5;55
color.horizscroll                 sgr 38;5;16;48;5;30
color.input                       sgr 38;5;222
color.interact                    bold
color.luacode                     
color.luaprefix                   bright cyan on blue
color.message                     default
color.modmark                     
color.popup                       
color.popup_desc                  
color.prompt                      
color.readonly                    sgr 38;5;28
color.selected_completion         sgr 38;5;16;48;5;254
color.selection                   sgr 38;5;16;48;5;179
color.suggestion                  sgr 38;5;239
color.unexpected                  default
color.unrecognized                sgr 38;5;203
color.yarn.module                 bright green
color.yarn.script                 bright blue
cwdhistory.limit                  100
debug.log_terminal                False
directories.dupe_mode             erase_prev
divider_line.commands             make nmake msbuild
doskey.enhanced                   True
exec.aliases                      True
exec.commands                     True
exec.cwd                          True
exec.dirs                         True
exec.enable                       True
exec.files                        False
exec.path                         True
exec.space_prefix                 True
files.hidden                      True
files.system                      False
fuzzy_history.ignore_ext          True
fuzzy_history.ignore_path         True
fuzzy_history.max_items           5000
fuzzy_history.max_time            25
fzf.default_bindings              True
fzf.exe_location                  
fzf.height                        40%
history.auto_expand               True
history.dont_add_to_history_cmds  exit history
history.dupe_mode                 erase_prev
history.expand_mode               not_quoted
history.ignore_space              False
history.max_lines                 10000
history.save                      True
history.shared                    False
history.show_preview              True
history.sticky_search             False
history.time_format               %F %T  
history.time_stamp                show
lua.break_on_error                False
lua.break_on_traceback            False
lua.debug                         False
lua.path                          
lua.reload_scripts                False
lua.show_match_type               True
lua.strict                        True
lua.traceback_on_error            False
lua.type_colors                   string=38;5;172 table=38;5;40 boolean=38;5;39 number=38;5;141 function=38;5;27 thread=38;5;203 types=38;5;244 nil=38;5;196
match.expand_abbrev               True
match.expand_envvars              True
match.fit_columns                 True
match.ignore_accent               True
match.ignore_case                 relaxed
match.max_fitted_matches          0
match.max_rows                    0
match.preview_rows                5
match.sort_dirs                   with
match.substring                   True
match.translate_slashes           system
match.wild                        False
prompt.async                      True
prompt.transient                  off
readline.hide_stderr              False
terminal.adjust_cursor_style      True
terminal.color_emoji              auto
terminal.differentiate_keys       False
terminal.east_asian_ambiguous     auto
terminal.emulation                auto
terminal.mouse_input              auto
terminal.mouse_modifier           
terminal.raw_esc                  False
terminal.use_altgr_substitute     True
tilde.autoexpand                  False
tilde.escape                      ~~
```

**Comment by chrisant996** [comment] 2023-09-18 06:06
> I tried it today. Both `DEL` and `C-d` can delete the entries. (Though it is strange my default key setting for remove an entry is `C-d` instead of `C-A-d`)

@ericsunplus Custom key bindings do not apply to inside commands that show popup windows or that operate in a "mode" (like the <kbd>Ctrl</kbd>-<kbd>R</kbd> history search command, and other history search commands).

Your key bindings do not affect what keys work inside the <kbd>F7<kbd> list.  The keys in the <kbd>F7</kbd> list are hard-coded.  Refer to the [Popup Windows](https://chrisant996.github.io/clink/clink.html#popupwindow) section of the documentation.

The default binding for <kbd>Ctrl</kbd>-<kbd>D</kbd> is `delete-char`, when the `clink.default_bindings` setting is `bash` as in the settings file you shared.  So, if you press <kbd>Ctrl</kbd>-<kbd>D</kbd> during reverse search mode, it checks whether any command is bound to the key -- if yes, then it cancels reverse search mode and invokes the command.  When using the .inputrc and settings you shared, the `delete-char` command is bound to <kbd>Ctrl</kbd>-<kbd>D</kbd>.  So that's what should get invoked.  Not `remove-history`.

> I simply want to delete an entry, like I do in `F7` or `clink-popup-history` mode. Exit or not exit the search mode is not a problem for me. But no matter I use `DEL` or `C-d` or `C-A-d` in reverse search mode, simply nothing happens. The entry don't get deleted and the reverse search mode is still active.

Ok, thanks for describing that.

Using the .inputrc and settings you shared, pressing <kbd>Del</kbd> or <kbd>Ctrl</kbd>-<kbd>D</kbd> during reverse search mode should cancel the mode and then delete the character under the cursor.  When I try it using the configuration info you shared, it cancels reverse search mode and deletes the character under the cursor.

When I use the configuration info you shared, and I press <kbd>Ctrl</kbd>-<kbd>Alt</kbd>-<kbd>D</kbd> during reverse search mode, it cancels reverse search mode and removes the history entry.

So, there must be more things different between our computers.

- What keyboard language is Windows using on your computer?
- Would you be willing to capture a Time Travel Debugging trace and share it?  It will be around 1 GB in size, so you'd have to upload it to a cloud file sharing system, and then send me a link to my direct email address.

To capture a Time Travel Debugging trace, you would do the following:
1. Download and install the [WinDbg Windows debugger](https://learn.microsoft.com/en-us//windows-hardware/drivers/debugger/).
2. Start cmd with Clink.
3. Use reverse search mode to search for a history entry.
4. Follow the steps for [Attach to a process](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/time-travel-debugging-record#attach-to-a-process) and attach to the cmd.exe that's in reverse search mode.
5. Switch to the cmd window and press <kbd>Ctrl</kbd>-<kbd>Alt</kbd>-<kbd>D</kbd>.
6. Switch to the tracer window and end the trace.
7. Upload the resulting .run file to a file sharing system (for example OneDrive or Google Drive or whatever you use).
8. Send to me a link to the file, at the email address in my github profile.

**Comment by ericsunplus** [comment] 2023-09-18 17:34
Hi Chris. sorry I am working on a company computer and the policy prohibit me from uploading any PC trace to cloud.

There are several language installed in my PC, when doing the experiments, I am using `English (United States) US Keyboard`. And `chcp` gives me `Active code page: 936`. I change it to US `437` or UTF8 `65001`, both not make a change.

Summary my problem
|  | `F7` | `clink-popup-history`| `C-R`|
|--------------------|------|-----------------------|-----|
| `DEL` | works | works | Don't work |
| `C-d` | works | works | Don't work |
|`C-A-d`| Don't work | Don't work | Don't work |

If there are nothing other than the trace can further show the root cause, I may live with current status. Thank you for the continuous help anyway.

**Comment by chrisant996** [comment] 2023-09-18 19:20
@ericsunplus Okay, the trace would be the fastest and most direct approach, but there are also other ways.

Try this:
- `clink set debug log_terminal true`
- Reproduce the problem.
- Share as much of the `clink.log` file as you can.  You don't need to share any of the stuff from injecting clink, near the top.  That's where it could contain sensitive information.

I need to see what key inputs Clink is actually receiving.

(If that doesn't give enough info, then I can iteratively add more logging to help eventually track it down.)

**Comment by ericsunplus** [comment] 2023-09-22 16:38
Hi @chrisant996 , email has been sent to you with the clink log

**Comment by chrisant996** [comment] 2023-09-22 18:04
> Hi @chrisant996 , email has been sent to you with the clink log

Hi @ericsunplus , I'm sorry but I don't seem to have received an email from you.   (I checked the Junk folder in case it got marked as junk email by mistake.)

Can you double check the address?
It should be "sparrowhawk996" followed by "@gmail.com".

**Comment by ericsunplus** [comment] 2023-09-24 03:29
Hi Chris,

Please check the screenshot.

Best Regards,
Eric

**Comment by chrisant996** [comment] 2023-09-24 06:37
> Hi Chris, Please check the screenshot. Best Regards, Eric

@ericsunplus There are no screen shots in any of the comments in this issue, and I haven't received any emails from you.

Is there a translation problem happening??

**Comment by ericsunplus** [comment] 2023-09-24 11:23
I was replying on Gmail and seems github only get the text and not the graph. Re-attaching here

![image](https://github.com/chrisant996/clink/assets/7379534/6e06649b-bb99-4242-a6d5-cf1afeef8784)

**Comment by chrisant996** [comment] 2023-09-24 16:07
The screenshot shows that you're using `fzf`.  You have Clink configured to start `fzf` when you press <kbd>Ctrl</kbd>-<kbd>R</kbd>.  `fzf` is a completely different program than Clink, and has its own key bindings.  It cannot modify the Clink history; it doesn't know about history or even about Clink.

Pressing <kbd>Alt</kbd>-<kbd>Shift</kbd>-<kbd>/</kbd> will invoke the `clink-what-is` command, and it will show what command is bound to whatever key is pressed next.  So pressing <kbd>Alt</kbd>-<kbd>Shift</kbd>-<kbd>/</kbd> then <kbd>Ctrl</kbd>-<kbd>R<kbd/> will show it's bound to `"luafunc:fzf_history"`, not the default which would be `reverse-search-history`.

**Closed** 2023-09-25 00:05 UTC
Labels: needs more information, question

**Comment by ericsunplus** [comment] 2023-09-25 08:03
OK Chris, thank you for pointing it out

**Comment by chrisant996** [comment] 2024-09-01 18:15
In Feb '24, I updated clink-fzf to add the ability to delete history entries (see https://github.com/chrisant996/clink-fzf/issues/11).
