### ISSUE TITLE
Keep quote on expansion

### ISSUE THREAD

**Issue by TheBrenny** [chrisant996/clink#9] opened 2020-10-12 23:13 UTC
Calling `cd "Progr` +  <kbd>TAB</kbd> in the `C:\` directory expands to `cd Program` (without the quote) because it registers that there is a folder named `ProgramData` along with the other two `Program Files` folders. The default behaviour should be to maintain the quote. Another alternative is to revert back to the original CMD method of escaping the slash.

Thoughts?

**Comment by chrisant996** [comment] 2020-10-14 10:28
Does removing the quote cause a problem?  If so, can you describe the problem?  That would help with prioritization.

Btw, this report led me to find #10 ("`menu-complete` has trouble with typed quotes").

While I don't disagree about preferred behavior, so far it seems the GNU Readline library has a different philosophy.  I'm trying to be cautious about what kind of changes I make to Readline.  Also I don't want to diverge too much, because I want to continue to take updates for Readline.

Which raises the question:  when Readline/Bash don't behave like CMD/Windows, what should happen?
- Behave like Readline?  I think that was the original intent behind Clink.
- Modify the Readline library to stop behaving like Readline?
- Modify the Readline library to add configuration settings for each individual quirk?
- Modify the Readline library to add a single configuration setting for "behave more like CMD" that controls all the quirks?

Backslashes are a great example -- Windows prefers backslash as the path separator, but Readline only accepts forward slash.  I made broad changes to Readline to enable the host to specify the preferred path separator, and Clink now specifies backslash.  While I expect that's probably wonderful for most Windows users, I can imagine there may be an audience for whom it's actually pretty terrible.

**Comment by chrisant996** [comment] 2020-10-15 00:32
Ah, interesting.  Both #9 and #10 are happening because of how I tried in d1f3ad5 to fix an issue where menu-complete gets stuck appending closing quotes to all completions even if they don't have an opening quote.  I'll need to revert that and find a better fix for it.

(Clink 0.4.8 reproduces the menu-complete quoting bug -- it's a bug in Readline, but the fix needed to be different than I thought at first.  And yes, I'll send all my Readline changes/fixes to Chet once I get to a point where things are in a good state and the fixes have had some real world testing to flush out regressions.)

**Comment by chrisant996** [comment] 2020-10-15 01:52
Fixed by ad405d2.

**Closed by chrisant996** 2020-10-15 01:52 UTC
Labels: bug
