### ISSUE TITLE
Ctrl+Space selected color not interpreted

### ISSUE THREAD

**Issue by oletf** [chrisant996/clink#495] opened 2023-09-18 14:07 UTC
Greetings,

I just updated from `0.4.9` to `1.5.5` and upon using the `Ctrl+Space` completion, all colors get properly displayed in : 
- the current line which is autocompleted on top
- the bottom "and $$$ more matches" on bottom

but the currently selected entrie in the list is marked by this `0;7` and I'm not sure if
it's an ansi color/font marker which is not correctly interpreted within Windows Terminal somehow, 
or a charset or even font problem...

default font used currently is `Cascadia Mono` and `chcp` gives `850`

```
C:\>dir "$WINDOWS.~BT\"
0;7$WINDOWS.~BT\
... and 14 more matches ...
```

Any insight on this ?
Thanks forward

**Comment by chrisant996** [comment] 2023-09-18 14:50
Duplicate of #493.

**Closed by chrisant996** 2023-09-18 14:50 UTC
Labels: bug, duplicate

**Comment by chrisant996** [comment] 2023-09-18 14:52
@oletf It only happens when both `colored-stats` and `colored-prefix-completion` in the .inputrc are `off` (which is the default when not using "Enhanced default settings").

**Comment by oletf** [comment] 2023-09-18 15:17
Thanks a lot, sorry I missed the duplicate!

**Comment by oletf** [comment] 2023-09-19 08:04
Weird edge cases are hiding everywhere !
You may have missed the thing before,
but now you've succeeded and that's what matters !
