### ISSUE TITLE
Installer has to be run twice for clink to be installed on top of an existing version

### ISSUE THREAD

**Issue by u01jmg3** [chrisant996/clink#231] opened 2022-01-28 10:16 UTC
Likely a hard one to diagnose and unfortunately I can't remember at what version this started happening but I'm finding that I must run the installer twice for clink to be installed.

Here's the scenario:

1. I open Windows Terminal and type `clink --version`
   - I get `1.3.3.d46fcb` as clink is already installed
1. I download clink `1.3.4`
1. I run the installer, it detects my previous installation settings and the setup finishes without issue.
1. I open Windows Terminal again and type `clink --version`
   - 'clink' is not recognized as an internal or external command,
operable program or batch file.
1. I run the installer again, it detects my previous installation settings and the setup finishes without issue.
1. I open Windows Terminal for a third time and type `clink --version`
   - I get `1.3.4.cf2dfb` and everything is as expected

**Comment by chrisant996** [comment] 2022-01-28 17:45
Are you installing with autorun?

I suspect that Clink is installing just fine, and that something is going wrong with autorun.

**Comment by chrisant996** [comment] 2022-01-28 18:02
I am unable to reproduce that.
Installing different versions one after the other successfully installs, and `clink --version` reports the newly installed version.

1. Do you have a Windows Terminal profile configured to run `clink inject`?
2. Or do you install with AutoRun enabled so that Clink automatically injects itself every time CMD is launched?
3. What does `clink set` report?  (When Clink is working.)
4. What does `clink info` report?  (When Clink is working.)

**Comment by u01jmg3** [comment] 2022-01-28 19:42
> _Are you installing with autorun?_

Yes

> _I suspect that Clink is installing just fine, and that something is going wrong with autorun._

Not sure that is the case. I just tried again by downgrading to `v1.3.3` and although setup completes without any error, I end up with a `bin` folder that has just `clink_dll_x86.dll`.

I realised I had an open Windows Terminal (I was using cmd) and thought that might be causing an issue. I closed Windows Terminal and attempted to upgrade back to `v1.3.4` and started to see errors with the installer.

<img width="316" alt="error1" src="https://user-images.githubusercontent.com/1266205/151609346-4b284437-867b-4986-9faa-38da30324c18.png">

<img width="317" alt="error2" src="https://user-images.githubusercontent.com/1266205/151609369-31b0ab95-850d-4e0a-9e62-00afed57b461.png">

<img width="317" alt="error3" src="https://user-images.githubusercontent.com/1266205/151609389-9ad70956-8377-4182-8e64-49e02299a327.png">

The third error can appear several times before the installer eventually finishes. Re-running the installer always sorts things out.

---

1. No. Correct with answer 2
2. \-
3. `clink set`
<details>
<pre>
autosuggest.async                 True
autosuggest.enable                False
autosuggest.original_case         True
autosuggest.strategy              match_prev_cmd history completion
clink.autostart
clink.colorize_input              True
clink.default_bindings            bash
clink.gui_popups                  False
clink.logo                        none
clink.paste_crlf                  space
clink.path
clink.promptfilter                True
cmd.admin_title_prefix
cmd.auto_answer                   off
cmd.ctrld_exits                   True
cmd.get_errorlevel                True
color.arg                         bold
color.arginfo                     yellow
color.argmatcher
color.cmd                         bold
color.cmdredir                    bold
color.cmdsep                      bold
color.comment_row                 bright white on cyan
color.description                 bright cyan
color.doskey                      bold cyan
color.executable                  sgr 38;5;120
color.filtered                    bold
color.flag                        default
color.hidden
color.horizscroll
color.input
color.interact                    bold
color.message                     default
color.modmark
color.popup
color.popup_desc
color.prompt
color.readonly
color.selected_completion
color.selection
color.suggestion                  bright black
color.unexpected                  default
color.unrecognized                sgr 38;5;220
debug.log_terminal                False
doskey.enhanced                   True
exec.aliases                      True
exec.commands                     True
exec.cwd                          True
exec.dirs                         True
exec.enable                       True
exec.files                        False
exec.path                         True
exec.space_prefix                 True
files.hidden                      True
files.system                      False
history.dont_add_to_history_cmds  exit history
history.dupe_mode                 erase_prev
history.expand_mode               not_quoted
history.ignore_space              False
history.max_lines                 10000
history.save                      True
history.shared                    False
history.sticky_search             False
lua.break_on_error                False
lua.break_on_traceback            False
lua.debug                         False
lua.path
lua.reload_scripts                False
lua.strict                        True
lua.traceback_on_error            False
match.expand_envvars              True
match.fit_columns                 True
match.ignore_accent               True
match.ignore_case                 relaxed
match.max_fitted_matches          0
match.max_rows                    0
match.preview_rows                5
match.sort_dirs                   with
match.substring                   False
match.translate_slashes           system
match.wild                        True
prompt.async                      True
prompt.transient                  off
readline.hide_stderr              False
terminal.adjust_cursor_style      True
terminal.differentiate_keys       False
terminal.east_asian_ambiguous     auto
terminal.emulation                auto
terminal.raw_esc                  True
terminal.use_altgr_substitute     True
</pre>
</details>

4. `clink info`
<details>
<pre>
version  : 1.3.4.cf2dfb
session  : 4860
binaries : C:\Program Files (x86)\clink\bin
state    : C:\Users\%USERNAME%\AppData\Local\clink
log      : C:\Users\%USERNAME%\AppData\Local\clink\clink.log
settings : C:\Users\%USERNAME%\AppData\Local\clink\clink_settings
history  : C:\Users\%USERNAME%\AppData\Local\clink\clink_history
scripts  : C:\Program Files (x86)\clink\bin ; C:\Users\%USERNAME%\AppData\Local\clink
inputrc  : %clink_inputrc%
             (unset)
         : state directory
             C:\Users\%USERNAME%\AppData\Local\clink\.inputrc
             C:\Users\%USERNAME%\AppData\Local\clink\_inputrc
         : %userprofile%
             C:\Users\%USERNAME%\.inputrc
             C:\Users\%USERNAME%\_inputrc
         : %localappdata%
             C:\Users\%USERNAME%\AppData\Local\.inputrc
             C:\Users\%USERNAME%\AppData\Local\_inputrc
         : %appdata%
             C:\Users\%USERNAME%\AppData\Roaming\.inputrc
             C:\Users\%USERNAME%\AppData\Roaming\_inputrc
         : %home%
             C:\Users\%USERNAME%\.inputrc
             C:\Users\%USERNAME%\_inputrc
</pre>
</details>
5. Double-clicking from my desktop. Note, I tried with Windows Terminal open and closed at the time I ran the installer.

---

> _This might also be due to interference from some other program on your computer. You may want to explore that possibility as well._

I haven't always had to run the installer twice and my PC setup hasn't changed significantly since then to my knowledge but I understand your point.

**Comment by chrisant996** [comment] 2022-01-28 20:01
Check your anti malware program's activity log.

If Clink files are disappearing out from under Clink while it's trying to use them, then this is probably interference from an anti malware suite.

(Clink can't do anything about that.)

**Comment by u01jmg3** [comment] 2022-01-28 20:19
I have checked (Windows Security) and there is nothing since Dec 26th. It is also setup to notify me so I'd know via a notification (which I'm not seeing).

> _If Clink files are disappearing out from under Clink while it's trying to use them, then this is probably interference from an anti malware suite._

This doesn't make sense. My anti-malware would always be blocking it, if that were the case. For example, why does a second install rectify things? To be clear, files are not disappearing out from under Clink because once I run the installer a second time and it installs, clink works without issue. Every time I run Windows Terminal, clink is operational.

**Comment by chrisant996** [comment] 2022-01-28 21:04
Thanks for the answers to the questions.  They help add context, but unfortunately they don't pinpoint anything.

Which checkboxes do you have checked in the installer?
Maybe there is something about the specific checkbox configuration?

**Comment by chrisant996** [comment] 2022-01-28 21:23
I am able to reproduce the problem when "Use versioned install directory" is unchecked.

I will see if there is a way to resolve the problem.

However, this may be exactly when Martin had made the installer always use a versioned install directory.

**Comment by u01jmg3** [comment] 2022-01-28 21:36
> _I am able to reproduce the problem when "Use versioned install directory" is unchecked._

I indeed uncheck this option. In fact, I think I was the one who requested it and at the time you said you had reservations about offering such an option.

<img width="316" alt="options" src="https://user-images.githubusercontent.com/1266205/151624876-c8f7fd72-97f9-4471-8c27-81c4f312e0f3.png">

**Comment by chrisant996** [comment] 2022-01-29 07:40
It is a bug/problem in the NSIS installer itself.  The `ExecWait` command that runs the uninstaller as the first step continues immediately, without actually waiting for the uninstaller to finish.  One way or another, it should be possible to find a workaround (without resorting to using "sleep for N seconds", since sleeping is unreliable).

**Closed** 2022-01-29 09:02 UTC
Labels: bug

**Comment by chrisant996** [comment] 2022-01-29 09:03
Phew.  That was a mess to track down and figure out how to trick NSIS into doing the right thing.  But it works now!  v1.3.5 should upgrade without this problem.

**Comment by chrisant996** [comment] 2022-01-30 20:02
Starting in v1.3.5 the installer no longer even has an option for a versioned directory, and the files go directly in the %ProgramFiles(x86)%\Clink directory.

It also now has an option to install with enhanced defaults.  That provides updated default settings that use Windows key bindings by default (rather than Unix/bash defaults where they conflict with Windows defaults), and enables full colorization by default.

@u01jmg3 Thank you for pushing on the "versioned install directory" thing!
