### ISSUE TITLE
removing and adding a new char in command causes new line inside cmd.exe

### ISSUE THREAD

**Issue by MagicAndre1981** [chrisant996/clink#356] opened 2022-09-29 17:23 UTC
Removing a character and adding a new char in command causes new line inside cmd.exe:

- press UP arrow key to get last command
- use left arrow key to navigate inside the command
- press backspace to remove 1 char
- now try to add a new char and for each new char you get a new line on screen, but if you press ENTER it runs the command fine

![image](https://user-images.githubusercontent.com/8274816/193100253-bd4c79f6-78ce-49f6-81d8-2a3f616908ba.png)

This looks to be a new issue since one of the last versions.

**Comment by chrisant996** [comment] 2022-09-30 00:13
I'm not able to reproduce it following those steps.

There must be more to it.  Can you help me with additional info?
- What codepage is in use?  Running `chcp` should say what codepage.
- What version of Windows is in use?
- Are you using ANSICON?
- Are you using the default console host in Windows, or are you using a custom one, or are you using any other utilities to enhance how the console/terminal works?
- When you use LEFT arrow key, specifically where does the cursor end up?
- Does the BACKSPACE need to wrap around from the left edge to the right edge?
- It looks like the input line wraps and takes multiple lines -- does the BACKSPACE need to happen on the second line, or on the first line?

And any other ideas you may have about what might influence the issue.

Yes, this is new in v1.3.43, as a side effect of having completely rewritten the display code, because of several problems in the Readline library's built in display code.  I tried to test it thoroughly, but there may be some special cases that I missed.

**Comment by MagicAndre1981** [comment] 2022-09-30 05:29
As you see in the top this cmd picture is from Windows 8.1 with the normal cmd.exe

```
C:\Users\André>chcp
Aktive Codepage: 850.
```

The issue happens after linebreak, so moving cursor from 2nd to 1st line.

**Comment by chrisant996** [comment] 2022-09-30 17:19
The repro steps look straightforward enough.  But I can't reproduce it on Win10.  So maybe it's somehow an issue with Win8.1's ANSI support.

As far as I can tell, Clink v1.3.43+ with the display rewrite should produce the same console output as v1.3.42 and earlier which used Readline's display routines.  But clearly I am missing something, and there is some unexpected difference.  Oh...or, I just realized, this issue might already exist in Readline on Win8.1, and Readline's implementation might merely trigger it much more rarely -- I did make a change to the math that decides _which_ optimized output style to use.

I'll try to see if I can find a difference.  But it turns out that I'm unable to find a difference, then @MagicAndre1981 could I ask you to do some diagnostic steps and send me the results?

(The main differences between the Readline display implementation versus the Clink custom rewrite should only be in edge cases where Readline's implementation has complex arithmetic errors.  The scenario here does not intersect with any of those edge cases.  And also Readline emits tons of separate outputs, but Clink emits a single complete output, which _hugely_ improves the behavior when resizing the terminal width.)

**Comment by MagicAndre1981** [comment] 2022-09-30 19:13
I also see this when I press several times the UP key to get latest commands. In 8.1, there is no easy resizing of the terminal width like in Windows 10.

Add some debug code and I can give you the log

**Comment by chrisant996** [comment] 2022-09-30 22:26
@MagicAndre1981 can you send two separate logs:

Run `clink set debug.log_terminal 1` to enable detailed input/output logging.

Then, capture two logs:
1. Using Clink v1.3.44:
  - Start Clink and make it cause an extra newline TWO times.
  - Copy/attach the clink.log file here.  It will get overwritten by the next steps, so be sure to copy/attach it before continuing.
2. Using Clink v1.3.42:
  - Do the same thing as above, but with the older Clink where the problem doesn't happen.
  - Please use _**exactly the same key presses**_ as above, so that I can compare the two logs.

Special Notes:
- Please make 2 extra newlines happen each time -- doing more than that will make it harder to compare the two logs.
- Please use exactly the same key presses and number of key presses for both cases, so that the logs can be compared.  If the key presses are different at all, it will make analysis more difficult and less reliable.

Thank you!  And sorry for the annoying bug.  😜

**Comment by dogancelik** [comment] 2022-10-02 00:41
I have the same issue, I reverted to `v1.4.42` for now.

I tried to log both versions [here](https://gist.github.com/dogancelik/fd60c4d8fe8d5d9570c621696d73221c), but it may not have the exact keypresses.

**Comment by chrisant996** [comment] 2022-10-02 05:22
> I have the same issue, I reverted to `v1.4.42` for now.
> 
> I tried to log both versions [here](https://gist.github.com/dogancelik/fd60c4d8fe8d5d9570c621696d73221c).
> 
> I use ConEmu v220308.

@dogancelik Wow, and you're using Win 10, even.  I wonder why I can't reproduce the problem.  I'll analyze the logs in the next couple of days and see what I can find.

**Comment by chrisant996** [comment] 2022-10-02 07:33
@dogancelik would you be able to share two things?

1. A copy of your prompt filter Lua script.
2. The output from `clink set`.

These should help me understand why the differences in the logs are happening.

**Comment by dogancelik** [comment] 2022-10-02 08:56
I don't have any custom prompt filters like git, but I am using [clink-completions](https://github.com/vladimir-kotikov/clink-completions).

This is my prompt:
```
$ set PROMPT
PROMPT=$E[m$E[32m$E]9;8;"USERNAME"$E\@$E]9;8;"COMPUTERNAME"$E\$S$E[92m$P$E[90m$_$E[90m$$$E[m$S$E]9;12$E\
```

[Clink set output](https://gist.github.com/dogancelik/fd60c4d8fe8d5d9570c621696d73221c/raw/a40c441e06fade633e22b9a771de21ff086fc1ef/clink_set.log)

**Comment by chrisant996** [comment] 2022-10-02 09:34
No success yet:  I'm using ConEmu, size 172x45, Clink v1.3.44, with the same prompt string.  I paste in the exact same 4 lines of text from the log you shared, and I move to the exact same cursor position, and press <kbd>Ctrl</kbd>-<kbd>W</kbd> 3 times.  But the display looks correct for me.

There is some elusive difference somewhere...  :(

@dogancelik Can you share your `.inputrc` file, if you have one?
Can you share your `ConEmu.xml` file from the ConEmu directory, or your `user-ConEmu.xml` from the Cmder\config directory if you're using Cmder?

**Comment by dogancelik** [comment] 2022-10-02 11:53
@chrisant996 No I am not using ANSICON. I uploaded the logs (correct line endings hopefully) and ConEmu, inputrc settings here: http://fh.dogancelik.com/clink.zip

**Comment by chrisant996** [comment] 2022-10-02 17:00
Yes, thanks, the logs have correct line endings now.  Unfortunately, still no repro, even after doing all of these:
- created a fresh profile
- using a fresh install of clink with no Lua scripts
- replaced my conemu.xml with yours
- replaced my clink_settings with yours
- replaced my .inputrc with yours

I'm analyzing the logs more deeply to see what differences exist in the output sequences.  The new display routines have three specific differences in what they output, but none of those three should be able to cause anything like this (1. in a couple cases they emit CR CR instead of CR but that is just a minor inefficiency that I'll clean up soon, 2. they emit ESC [ _col_ G to jump to column _col_ instead of emitting + _col_ ESC [ C to move right _col_ columns, 3. they emit the entire output as a single string, instead of emitting tons of tiny strings like Readline does, which makes Readline slower).

So, I anticipate/hope to find a fourth difference of some kind in the logged output, which will hopefully be a clue to point me in the right direction to figure this out.

Otherwise, maybe it is related to codepage/locale??

@dogancelik What does `chcp` report for you?

**Comment by dogancelik** [comment] 2022-10-03 00:52
@chrisant996 I use `chcp 65001`.

Here's a demo, just in case.
![clink bug](https://user-images.githubusercontent.com/486818/193484461-8b93610e-91b7-4d3f-a742-62aa147aecf7.gif)

**Comment by chrisant996** [comment] 2022-10-03 04:47
@dogancelik Yes, thanks for helping track it down. What you experienced is https://github.com/Maximus5/ConEmu/issues/2429 which was a regression in ConEmu. The reason it didn't affect Clink before v1.3.43 is that I replaced the Readline display routines with a more efficient custom implementation. Writing the entire output in a single more efficient API call exposes the ConEmu regression.

@MagicAndre1981 is experiencing a similar issue in the Windows 8.1 built-in conhost.  I'll try to find a Win 8.1 machine somewhere.  I bet that the more efficient output is exposing the old line wrapping bug in Windows that got fixed in Win 10 (there was some discussion about it in the ConEmu and Windows Terminal repos a while back, and I'd forgotten about that).  I may be able to work around it by simply disabling the new efficiency smarts.

Re: Win 10 and 11 -- I use both of those daily, and both are working fine for both the default console and Windows Terminal.

**Comment by MagicAndre1981** [comment] 2022-10-03 06:17
> @MagicAndre1981 is experiencing a similar issue in the Windows 8.1 built-in conhost. I'll try to find a Win 8.1 machine somewhere.

get it from the [link](https://software.download.prss.microsoft.com/dbazure/Win8.1_English_x64.iso?t=18abc969-51ec-449a-a891-aee469fadd9a&e=1664844061&h=aec310a7a42b89ef949d62b2fc7c6b2d1ff6551716dadef4d2b7e5273c62c323) and install a VM.

I'll try to capture now the logs

**Comment by MagicAndre1981** [comment] 2022-10-03 06:58
I removed some things before to only show the same actions:

[clink_142.log](https://github.com/chrisant996/clink/files/9695257/clink_142.log)
[clink_144.log](https://github.com/chrisant996/clink/files/9695258/clink_144.log)

**Comment by chrisant996** [comment] 2022-10-03 16:48
> I removed some things before to only show the same actions:
> 
> [clink_142.log](https://github.com/chrisant996/clink/files/9695257/clink_142.log) [clink_144.log](https://github.com/chrisant996/clink/files/9695258/clink_144.log)

Yay!  I see the difference in the output.  And indeed the Win8.1 console behaves differently than the Win10+ console for line wrapping.  It is indeed the old line wrapping bug that was fixed in Win10+ as part of the Windows Terminal effort (the issue is whether the cursor wraps immediately when it reaches the right edge, or if wrapping is deferred until the next output that is printed).

I see a few options for how I can fix this.

Thank you, @MagicAndre1981 for reporting this and for sharing logs!

**Closed** 2022-10-04 00:05 UTC
Labels: bug

**Comment by MagicAndre1981** [comment] 2022-10-04 16:55
I'll test it when new version is released

**Comment by chrisant996** [comment] 2022-10-04 19:05
@MagicAndre1981 v1.3.45 is published.

**Comment by MagicAndre1981** [comment] 2022-10-04 20:33
> @MagicAndre1981 v1.3.45 is published.

ok, when my new line issue is gone, but when I press UP key, the last command is now corrupted. Also copying text is not correctly pasted. But this only happens some times, not always.

**Comment by chrisant996** [comment] 2022-10-04 22:06
@MagicAndre1981 Can you share three things:
- Your `clink_history` file.  For privacy, you can email it to the address in my github profile.  I delete such things as soon as I finish analyzing them.
  - Or, you can narrow it down to a subset of your `clink_history` file, and just share an excerpt that reproduces the issue.
- The terminal width in columns.
- A screen shot of the prompt.

Then I can use those to reproduce what you're seeing.

I used <kbd>Up</kbd> through my entire command history on both Win 10 and Win 8.1 (5431 history entries) and experienced no issues.  So there is likely a specific edge case that you're hitting, which is not present in my command history.

**Comment by MagicAndre1981** [comment] 2022-10-05 06:49
> **UPDATE:** I think I've found the cases you were hitting. Please try this build: [clink.1.3.46.d6fdd0.zip](https://github.com/chrisant996/clink/files/9711993/clink.1.3.46.d6fdd0.zip) 

the .46 work fine now

**Comment by chrisant996** [comment] 2022-10-05 20:56
Great, thanks for confirming. v1.3.46 is published now with the fix (and also a fix for right-side prompts on Win8.1, which worked before).

**Comment by mcoret** [comment] 2022-10-14 22:36
I think I have an issue, related to the discussed one. I have Windows 11, and whenever I'm searching through the history matches, longer lines from the history stay on the command line, only partially replaced with shorter history matches. This often leads to unreadable results, shown on the command line. I'm on the latest release.

**Comment by chrisant996** [comment] 2022-10-15 00:15
> I think I have an issue, related to the discussed one. I have Windows 11, and whenever I'm searching through the history matches, longer lines from the history stay on the command line, only partially replaced with shorter history matches. This often leads to unreadable results, shown on the command line. I'm on the latest release.

Are you using ConEmu?  Are you using the latest ConEmu?  There was a recent breakage in ConEmu that can cause that.

**Comment by mcoret** [comment] 2022-10-15 01:51
I am using Windows Terminal and CMD, and both of them have the same issue.

**Comment by chrisant996** [comment] 2022-10-15 02:23
@mcoret ok that's interesting.  I'm not able to reproduce anything like that.

Can you please share all of the following information?  You can attach them here or email them to the address in my github profile.
- Your `clink_history` file.
- Your `clink_settings` file.
- Specific steps -- e.g. type `blah` then press <kbd>Up</kbd> about 20 times until the `blah asaksjdhfkljhasdlkfjhaslkdjflasjdhf` history line shows up.

Thanks!

**Comment by mcoret** [comment] 2022-10-15 03:26
Here are the files. I've redacted the username in the info, but apart from that everything is unchanged.
I have the default prompt string `$p$g`. I can reproduce the issue by typing `g` and then pressing `Up` 4 times, then by pressing `Down` the command line isn't clearing up completely.
Thank you!

[clink.zip](https://github.com/chrisant996/clink/files/9791062/clink.zip)

**Comment by chrisant996** [comment] 2022-10-15 16:53
@mcoret Thank you for the files -- I am able to reproduce the problem!  Will track it down and get a fix out ASAP.

**Comment by chrisant996** [comment] 2022-10-15 17:38
To hit the bug, it was necessary to have something like this:

Before:
```plain
whatever> aaa_whatever_this_part_does_not_matter_aaa IDENTICAL DIFFERENT
something that wrapped
```

After:
```plain
whatever> bbb_whatever_this_part_does_not_matter_bbb IDENTICAL
```

And then the optimization had a slightly wrong condition, about whether the end of the display needed to be cleared.

Your history file contains cases of that.  Apparently my own 5400+ entry history file does not.  ¯\_(ツ)_/¯

Thanks for catching and reporting this, @mcoret !

**Comment by mcoret** [comment] 2022-10-15 18:58
all is fine! thank you for your great work!

**Comment by mcoret** [comment] 2022-10-18 11:50
Hi!
Can you please check the following history file?
I'm experiencing a similar problem when pressing `a` (or `x`) and then, after pressing `Up` three times and then `Down`, the command line isn't clearing up completely. Note there is a trailing `space` character in some of the fields.
Thank you!

[clink_history.txt](https://github.com/chrisant996/clink/files/9809978/clink_history.txt)

**Comment by chrisant996** [comment] 2022-10-19 02:15
@mcoret, thank you for the excellent repro steps.  `a` then <kbd>Up</kbd> x3 is enough to hit the issue.  Pressing <kbd>Down</kbd> after that hits the issue again.

The trailing `space` is indeed the trigger.  Another misguided optimization.  Sorry about that!

Thanks for reporting it; I'll publish an update shortly.
