### ISSUE TITLE
Failed to inject (Host validation failed)

### ISSUE THREAD

**Issue by elieux** [chrisant996/clink#123] opened 2021-05-31 11:09 UTC
Hey.  I've been getting errors from Clink lately.  It says *Failed to inject* (although it seems like everything's working anyway) and the log file says *Host validation failed*.  I tried several versions and I can see the issue is not present in v1.2.2.e69258 and is present in v1.2.4.b30d68 and newer, including v1.2.9.329839.  Curiously, v1.2.2 still shows *Host validation failed* in the log.

My *HKCU\SOFTWARE\Microsoft\Command Processor\Autorun* is set to:
```
chcp 65001 >nul & set GIT_SSH=plink.exe & set PYTHONIOENCODING=UTF-8 & set PROMPT=$E[1;32m%username%@%computername%$S$E[33m$P$S{git}$_$E[1m$G$E[0m & "%APPS%\clink\clink" inject --profile "%USERPROFILE%\.clink" >nul
```

I usually run ConsoleZ, but the issue is also present in the standard terminal.

Please advise.

**Comment by elieux** [comment] 2021-05-31 11:17
Ah, nevermind.  I read the code and apparently `--autorun` is all I needed to fix the problem.  You can close this ticket, but I'm curious why *Host validation failed* keeps appearing.

**Comment by chrisant996** [comment] 2021-05-31 15:34
This is a good catch, thanks for reporting it!

I'm pretty sure it's only happening sometimes, right?  "Host validation failed" occurs when the CMD instance will not be interactive.  In that case Clink avoids injecting itself, since it won't actually get used at all.

The error message is pretty oblique... But also there's not much point in showing an error message in that case anyway, since there can be no expectation of Clink "working" in that case, so there can be no sense of it "failing".

I'll remove the error message entirely in that case, but still let it report the failure in the log, and with a more informative message in the log.

I'll close this issue when the fix is committed.

**Closed** 2021-05-31 16:01 UTC

**Comment by chrisant996** [comment] 2021-05-31 16:14
Ha. #107 was for the same issue, but I only suppressed the error message in the autorun case. Wasn't thinking clearly, I guess -- of course it should never report it as a failure (until/unless future me says I wasn't thinking clearly now, either 🤣).  Or to be fair, maybe I chose to make a targeted fix with minimal chance of regression -- yeah, I'll go with that interpretation.

**Comment by elieux** [comment] 2021-06-01 07:01
> with a more informative message in the log

Nice.

> I only suppressed the error message in the autorun case

Depends.  I support failing loudly and I would gladly consider an explicit inject (which is how my autorun was actually set up) in a non-interactive shell a failure.

**Comment by chrisant996** [comment] 2021-06-01 08:27
It isn't a "failure": there's nothing "wrong" with trying to inject Clink into a non-interactive shell.  As a performance optimization, Clink just declines to actually inject itself in that case, since there's no benefit.
