### ISSUE TITLE
cursor position sometimes gets moved unexpectedly

### ISSUE THREAD

**Issue by jtnord** [chrisant996/clink#262] opened 2022-03-25 18:30 UTC
in some (as yet unknown) circumstances cmd.exe when used in windows terminal with clink gets confused about the position of the cursor and typing just leads to the console echoing in a line above making things unreadable.

I have not observed this without clink being injected, which is why I beleive this is a clink issue and not a windows terminal issue

I am also unsure how to get into this state but it happens frequently.

As it is hard to describe see the attached video.

https://user-images.githubusercontent.com/494726/160180263-3c77167e-3911-4b09-b351-8e2e8665812e.mp4

`Clink v1.3.12.f70397`  (was also observed with earlier versions)
Windows 11 21H2
Windows Terminal 1.11.3471.0

**Comment by chrisant996** [comment] 2022-03-26 01:12
Let's start the troubleshooting with three things:

1. Can you please share the output from `clink set`?
2. Can you please try enabling terminal logging:
    - Run `clink set debug.log_terminal true` to enable terminal logging.
    - Reproduce the problem.
    - Attach the resulting `clink.log` file in a reply here.  (Use `clink info` to find where the log file is located.)
    - If the output is coming from Clink itself, the terminal logging should show what is being output.
3. Try turning off autosuggest:  `clink set autosuggest.enable false`.
    - It could be that a Lua script match generator is printing output.  Since the autosuggest feature runs match generators in the background while you type, it could be causing the match generator script's output to occur at an especially troublesome moment.  Match generators should not output anything to the terminal; if they do, it will garble the display.
    - If turning that off resolves the issue, then the next step will be to inspect the match generator scripts.

**Comment by chrisant996** [comment] 2022-03-30 07:59
@jtnord I'm happy to help troubleshoot what is happening.  Let's start with the troubleshooting steps in my previous response.

**Comment by chrisant996** [comment] 2022-04-07 16:03
@jtnord I look forward to troubleshooting this with you.  Please reopen this issue when you have a chance to respond.  Thanks!

**Comment by jtnord** [comment] 2022-04-14 16:15
> Can you please share the output from clink set

```
autosuggest.async                 True
autosuggest.enable                True
autosuggest.original_case         True
autosuggest.strategy              match_prev_cmd history completion
clink.autostart
clink.colorize_input              True
clink.default_bindings            bash
clink.gui_popups                  False
clink.logo                        full
clink.paste_crlf                  crlf
clink.path
clink.promptfilter                True
cmd.admin_title_prefix
cmd.auto_answer                   off
cmd.ctrld_exits                   True
cmd.get_errorlevel                True
color.arg                         bold
color.arginfo                     sgr 38;5;172
color.argmatcher                  sgr 1;38;5;40
color.cmd                         sgr 1;38;5;231
color.cmdredir                    sgr 38;5;172
color.cmdsep                      sgr 38;5;214
color.comment_row                 sgr 38;5;87;48;5;18
color.description                 sgr 38;5;39
color.doskey                      sgr 1;38;5;75
color.executable                  sgr 1;38;5;33
color.filtered                    sgr 38;5;231
color.flag                        sgr 38;5;117
color.hidden                      sgr 38;5;160
color.horizscroll                 sgr 38;5;16;48;5;30
color.input                       sgr 38;5;222
color.interact                    bold
color.message                     default
color.modmark
color.popup
color.popup_desc
color.prompt
color.readonly                    sgr 38;5;28
color.selected_completion         sgr 38;5;16;48;5;254
color.selection                   sgr 38;5;16;48;5;179
color.suggestion                  sgr 38;5;239
color.unexpected                  default
color.unrecognized                sgr 38;5;203
debug.log_terminal                False
doskey.enhanced                   True
exec.aliases                      True
exec.commands                     True
exec.cwd                          True
exec.dirs                         True
exec.enable                       True
exec.files                        False
exec.path                         True
exec.space_prefix                 True
files.hidden                      True
files.system                      False
history.dont_add_to_history_cmds  exit history
history.dupe_mode                 erase_prev
history.expand_mode               not_quoted
history.ignore_space              True
history.max_lines                 25000
history.save                      True
history.shared                    False
history.sticky_search             False
lua.break_on_error                False
lua.break_on_traceback            False
lua.debug                         False
lua.path
lua.reload_scripts                False
lua.strict                        True
lua.traceback_on_error            False
match.expand_envvars              True
match.fit_columns                 True
match.ignore_accent               True
match.ignore_case                 relaxed
match.max_fitted_matches          0
match.max_rows                    0
match.preview_rows                5
match.sort_dirs                   with
match.substring                   True
match.translate_slashes           system
match.wild                        True
prompt.async                      True
prompt.transient                  off
readline.hide_stderr              False
terminal.adjust_cursor_style      True
terminal.differentiate_keys       False
terminal.east_asian_ambiguous     auto
terminal.emulation                auto
terminal.mouse_input              off
terminal.mouse_modifier
terminal.raw_esc                  False
terminal.use_altgr_substitute     False
```

> Can you please try enabling terminal logging:

enabled will update when it happens again.

> Try turning off autosuggest: clink set autosuggest.enable false.

I had this also with a previous installation on a different laptop that did not have the autosuggest enabled, so I do not think it is that.

**Comment by jtnord** [comment] 2022-04-14 16:18
@chrisant996 I do not have permissions to re-open.

**Comment by pukkandan** [comment] 2022-04-14 16:54
> I do not have permissions to re-open.

If a maintainer closes an issue, users cannot re-open it. They can only re-open issues that they themselves closed.

**Comment by jtnord** [comment] 2022-04-20 17:08
happened just now, log attached.

[clink.log](https://github.com/chrisant996/clink/files/8523706/clink.log)  

terminal : Version: 1.12.10733.0
clink:  1.3.12.f70397

**Comment by chrisant996** [comment] 2022-04-20 17:37
It's a very long log.  I should have mentioned that a screen shot is also needed, so that I can deduce which part of the log corresponds to the screen, and so that I can see what the result was, in addition to what the output was.

**Comment by jtnord** [comment] 2022-04-20 18:34
Does the log need to be enabled from the start?

The terminal window still running and I can run some more commands and capture a new video and details and add the log for just the end

**Comment by chrisant996** [comment] 2022-04-20 19:16
It doesn't need to be enabled from the start.  But don't switch it on/off multiple times in the same log file, as that would make it very difficult to make sense of the logging.

Also, can you share the width of the terminal?  The log doesn't include the width or height of the terminal (I'll add it for the future), and the width greatly affects how Readline updates the display, so it isn't possible to analyze/replay the log accurately without knowing the terminal width.

Thanks!

**Comment by chrisant996** [comment] 2022-04-20 19:32
I'm pretty sure this is a problem with your font.  I think one or more of the characters in your custom prompt string render as a different width than the character is supposed to be.  Which then ruins the math for how to position the cursor.

Can you share a link to the font you're using?

**Comment by jtnord** [comment] 2022-04-21 11:49
font is DejaVu Sans Mono NF  -> https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/DejaVuSansMono/Regular/complete/DejaVu%20Sans%20Mono%20Nerd%20Font%20Complete.ttf 

filter scripts -> https://github.com/jtnord/clink_scripts

active code page is 650

font size is 11,  I have multiple screens some have different DPI settings.


> Are you able to make it happen consistently, using a particular set of steps? If so, then we can use Time Travel Debugging to capture an execution session on your computer, and then I can debug it later on another machine. Let me know if you're able to make it happen consistently, and I will send a link for how to capture a Time Travel Debugging trace.

I can not reliably make it happen but it does consistently happen but sometimes after a day or so.

I notice it mostly after running a command that I have interrupted with ctrl+c  (like a maven build)  but this may not always be the case.

width is currently in a window where I see this 176 characters

**Comment by jtnord** [comment] 2022-04-21 12:02
[trimmed clink.log](https://github.com/chrisant996/clink/files/8530742/clink.log)

https://user-images.githubusercontent.com/494726/164453943-749efbf4-0315-4ea4-aaf5-5eb27620a65b.mp4

**Comment by jtnord** [comment] 2022-04-21 12:32
about the `120` width.  this is generally the default for the start of terminal.  I then often resize it.  looking at the trimmed clink log does clink beleive the terminal is still 120 characters wide?

for some reason when I run `set` I see `COLUMNS=120`  which is a bit iffy...  I do not set that...

**Comment by chrisant996** [comment] 2022-04-21 15:52
### Re: COLUMNS=120
The `COLUMNS=120` was surprising, so I debugged that.  It turns out the `set` command in cmd.exe looks at a _snapshot_ of the environment, not the actual live environment.  Readline updates `COLUMNS` in the live environment, but the `set` command won't notice until some invocation of `set` sets a variable (versus getting a variable), at which time the `set` command takes a new snapshot of the environment.  However, Readline and Clink always look at the live environment when getting environment variables, so they aren't affected by that quirk.

But, Readline only uses the `COLUMNS` value if it wasn't able to get the actual console dimensions from the OS.  And with Clink, it always gets the actual console dimensions, so the `LINES` and `COLUMNS` variables are only informational for other programs.

For consistency, I've made a change to force cmd.exe to update its environment snapshot on each new edit prompt, so that `set COLUMNS` will report accurately in the new edit prompt after the terminal has been resized.  (There's no way to force cmd.exe to update the snapshot on the fly as the terminal is resized, at least not without starting a new prompt each time, which would be pretty disruptive.)

### Re: code page 650
What language and system locale are you using?
Windows and wikipedia and several other sources are all telling me that 650 is an invalid code page.
Could it be that the active code page on your system is 65001, which would be UTF-8?

### Re: the latest trimmed log file
Good: replaying the log on my computer produces the exact same results as in the video.  So, we now know for sure that Readline is indeed somehow the source of the problem.

And: the log shows that Readline indeed believes that the terminal width is 120, not 176.

... are you by any chance using a Clink that you built locally, perhaps with Mingw64?  I do see a way in the Readline source code for this exact problem to occur if Clink is built with Mingw64 (but not with Mingw32) -- in which case it will accidentally use the `COLUMNS` environment variable instead of the actual terminal dimensions.

**Comment by chrisant996** [comment] 2022-04-21 16:04
> I can not reliably make it happen but it does consistently happen but sometimes after a day or so. during that time I may have sensitive information going through the terminal (would a time travel debug capture this?)

Time Travel Debugging would capture only what cmd.exe itself sees.  If the sensitive information is going through other programs and not cmd.exe, then the TT trace would not capture it.

But also, Time Travel Debugging generates large volumes of data very quickly, and it also slows down the program significantly, so it isn't something that can be left running for an extended period of time (well, there's a way to use a circular trace buffer, but let's not mess around with that).

At this point, I think the best thing to do is add a bit more logging to identify why/when Readline gets confused about the terminal width.

**Comment by jtnord** [comment] 2022-04-22 11:01
Sorry typo, it is `850` (British English).

I occasionally do change to UTF8 for a single cmd.exe session but had not done that here (for either the cmd.exe session or since last boot of windows - so you can treat this as `850` for the purpose of the bug)

> At this point, I think the best thing to do is add a bit more logging to identify why/when Readline gets confused about the terminal width.

👍

**Comment by chrisant996** [comment] 2022-04-23 18:31
Ah!  I finally figured out a way to reproduce the problem.

**Do you resize the terminal while a program is running?**
E.g. maybe while Maven is running, or some other program is running?

Readline does not notice the terminal has changed size if it changes while a program is running -- it only notices if the terminal size is changed while the Readline line editor is active.  That is easy for Clink to compensate for and fix.

**Comment by chrisant996** [comment] 2022-04-23 19:01
I expect this should be fixed in v1.3.16 now.

**Comment by jtnord** [comment] 2022-04-25 12:59
>> Do you resize the terminal while a program is running?
>E.g. maybe while Maven is running, or some other program is running?

yes.

**Comment by chrisant996** [comment] 2022-04-25 14:10
Great, thanks for confirming. 😎

**Closed** 2022-04-25 14:10 UTC
Labels: bug, external
