### ISSUE TITLE
Clink Tab completion is different than it shows

### ISSUE THREAD

**Issue by midenok** [chrisant996/clink#475] opened 2023-08-09 07:45 UTC
I don't know why it works like that, but it's counterintuitive. It shows:

![image](https://github.com/chrisant996/clink/assets/3307037/6073f877-58a3-499f-b942-62fd71860efd)

After pressing Tab:

![image](https://github.com/chrisant996/clink/assets/3307037/e40e7c49-f942-43f9-a6d9-c730b4c5d4db)

Maybe there is different hotkey for complete what it shows, but I couldn't find it.

**Comment by chrisant996** [comment] 2023-08-09 09:26
P.S.  I would like to add some kind of hint or tip text (maybe below the input line) to help introduce the Auto-suggest feature to users who aren't accustomed to it.  But I'm concerned about always showing text that's only helpful the first couple of times, or showing text that's distracting.

Out of curiosity, if the [Getting Started](https://chrisant996.github.io/clink/clink.html#getting-started) section of the documentation was read, is there something that could be added to help make the Auto-suggest feature more clear?  I've considered trying to add some pictures, but my sense is that there is already more documentation than most people want to read, and that it would be more useful for Clink itself to have built-in introductions for certain features.  Auto-suggest is the one feature that is "in your face" even when not actively being used.  That sets it apart from other features and makes it a candidate for some kind of active help/introduction/tutorial.  But I haven't yet been able to think of a non-invasive way to do that for the Auto-suggest feature.

**Comment by chrisant996** [comment] 2023-08-09 09:56
Also, #280 has some discussion related to this issue, and might be helpful to read.
And, #440 is a duplicate of this issue.

**Closed** 2023-08-14 16:00 UTC
Labels: duplicate, question, working as intended

**Comment by midenok** [comment] 2023-08-23 00:28
@chrisant996 You can add to the end of auto-suggest text ` (auto-suggest: press Right/End)` and make it possible to turn off via `clink set auto_suggest_hint False`.

@chrisant996 Yes, docs are pretty comprehensive, but who reads docs completely these days? There are main tasks to solve and a million of things to tune-up that are not directly related to the task (clink, conemu, Far, winrar, chocolatey, cygwin, git, etc.). So you want them just work and preferable preinstalled and preconfigured correctly. But yes, I did some research against "completion" because I didn't know this is different feature "auto-suggest".

I just had a glance at **How Completion Works** section and found a reference to Auto-suggest in the end. But instead of:

> See also [Auto-suggest](https://chrisant996.github.io/clink/clink.html#gettingstarted_autosuggest) for information about auto-suggestions, which by default show up in gray at the end of the input line. Completions are for words, and Auto-suggestions are for the whole input line (for example, based on history).

I'd write this:

Pressing `Right` or `End` finishes [auto-suggested](https://chrisant996.github.io/clink/clink.html#gettingstarted_autosuggest) text (shown up in gray at the end of the input line). Don't confuse two terms: **Completions** are for words, and **Auto-suggestions** are for the whole input line (for example, based on history).

Thus I'd see all the hotkeys in the section and probably had all answers without the requirement for careful reading.

**Comment by chrisant996** [comment] 2023-08-23 01:27
> @chrisant996 You can add to the end of auto-suggest text ` (auto-suggest: press Right/End)` and make it possible to turn off via `clink set auto_suggest_hint False`.

I already prototyped two different variations on that (source code is in d047fed68f00604b82837cc2308a7d9f119d8108).  It looks terrible, it's confusing, and it still isn't really clear about the difference between auto-suggest vs completion, nor about what Right/End will actually do.

I'm continuing to explore options for that, but it does not look promising.

> @chrisant996 Yes, docs are pretty comprehensive, but who reads docs completely these days? There are main tasks to solve and a million of things to tune-up that are not directly related to the task (clink, conemu, Far, winrar, chocolatey, cygwin, git, etc.). So you want them just work and preferable preinstalled and preconfigured correctly. But yes, I did some research against "completion" because I didn't know this is different feature "auto-suggest".

Yes.  Everyone wants documentation to only contain text about the thing they're looking up right now, and nothing else.  😂  It's human nature.

> I just had a glance at **How Completion Works** section and found a reference to Auto-suggest in the end.  But instead of:
> 
> > See also [Auto-suggest](https://chrisant996.github.io/clink/clink.html#gettingstarted_autosuggest) for information about auto-suggestions, which by default show up in gray at the end of the input line. Completions are for words, and Auto-suggestions are for the whole input line (for example, based on history).

I've been working on rewriting those parts of the docs, and also adding some visual examples in the auto-suggest section.

> I'd write this:
> 
> Pressing `Right` or `End` finishes [auto-suggested](https://chrisant996.github.io/clink/clink.html#gettingstarted_autosuggest) text (shown up in gray at the end of the input line). Don't confuse two terms: **Completions** are for words, and **Auto-suggestions** are for the whole input line (for example, based on history).
> 
> Thus I'd see all the hotkeys in the section and probably had all answers without the requirement for careful reading.

It sounds like you're suggesting to make the Completion section document both completions and auto-suggestions, and list the keys for both.  There need to be separate sections on the separate features (for many reasons).  But perhaps I can explore making the Getting Started area of the docs have a section about "Typing Savers" which jumbles together those features at first.

I'm working on adjustments to the docs, and I recommend checking and commenting on the Getting Started section again after v1.5.4 is published.

(Phrases like "don't confuse two terms" tend to cause feedback that documentation is abrasive or condescending; I try to find more neutral or positive phrasing.)

**Comment by chrisant996** [comment] 2023-08-23 01:35
Or I'm also considering adjusting the Getting Started part of the documentation to be more organized a little more like the front page of the [fish shell](https://fishshell.com/) documentation.  Since auto-suggestions are "in your face", it's reasonable to make them the first thing covered in the documentation, even before completions.

P.S. The auto-suggestions feature is modeled after fish.  And fish doesn't add on-screen markup about keys for accepting suggestions (and based on the prototyping I've done so far, I think it's very good that fish doesn't 😉).

**Comment by chrisant996** [comment] 2023-08-24 18:13
@midenok The documentation adjustments have been published.
- Landing site: https://chrisant996.github.io/clink/
- Documentation: https://chrisant996.github.io/clink/clink.html
