### ISSUE TITLE
v1.3.48 flagged as trojan by windows

### ISSUE THREAD

**Issue by krish-gh** [chrisant996/clink#366] opened 2022-10-20 10:49 UTC
![image](https://user-images.githubusercontent.com/2088089/196929179-ac3239c0-082e-4995-93e4-efafa72836a8.png)

**Comment by pukkandan** [comment] 2022-10-20 12:54
Duplicate of https://github.com/chrisant996/clink/issues/34 https://github.com/chrisant996/clink/issues/54 https://github.com/chrisant996/clink/issues/138 https://github.com/chrisant996/clink/issues/190 https://github.com/chrisant996/clink/issues/298 https://github.com/chrisant996/clink/issues/318

imo one of these issues should be pinned so that people dont keep asking the same

**Comment by theytaz** [comment] 2022-10-20 13:16
Also curious, would it be triggered if the binaries are signed?

**Closed** 2022-10-20 14:06 UTC
Labels: external

**Comment by chrisant996** [comment] 2022-10-20 15:07
> Also curious, would it be triggered if the binaries are signed?

That would depend on specific AV suites.

But since I'm not a company with multiple employees, it is not possible to get an EV code signing cert.

And even if it were possible, the certs cost several hundred dollars per year.

**Comment by chrisant996** [comment] 2022-10-20 15:11
> imo one of these issues should be pinned so that people dont keep asking the same

I'll create an issue and pin it. But it won't help as much as we'd hope: often people simply click New Issue without visiting the Issues page. For example, in the mridgers repo, many people have kept creating new issues despite an issue saying that the repo is dead and pointing at the new repo (with eye-catcher icons in its title, even).

**Comment by pukkandan** [comment] 2022-10-21 08:14
My experience is that it somewhat helps. There will always be people who keep opening duplicates, but more people will look at pinned issues than closed issues
