### ISSUE TITLE
 Change auto completion key

### ISSUE THREAD

**Issue by Mqxx** [chrisant996/clink#540] opened 2023-12-18 09:25 UTC
Hey, currently the autocomplete key is set to <kbd>arrow right</kbd>. Is it possible to set it to another key? For example on <kbd>TAB</kbd> like under Linux?

I would prefer an experience for autocomplete like in an IDE, where I confirm the current selection with <kbd>TAB</kbd>.

Thanks ~Mqx

**Comment by chrisant996** [comment] 2023-12-18 12:08
@Mqxx I'm sorry but I think you're mixing up "auto-suggestions" versus "completions".  They're different features for different purposes.

For example see [Feature Highlights](https://chrisant996.github.io/clink/clink.html#features).

Tab already is the completion key, and the are a few different styles of completion commands (not to be confused with auto-suggestions).  Have you looked at the documentation on setting key bindings?

**Comment by chrisant996** [comment] 2023-12-18 12:14
Duplicate of #475.

**Comment by Mqxx** [comment] 2023-12-19 12:31
Ahh okay I see. Thanks. Yea I think out of my intuition I would press TAB when I see the gray auto suggestion.

**Comment by Mqxx** [comment] 2023-12-19 12:41
I now understand the difference between auto-suggestion vs. competion. But is it still possible to complete the suggestion using <kbd>TAB</kbd> instead of the <kbd>arrow right</kbd>?

**Comment by chrisant996** [comment] 2023-12-19 16:27
I really don't think that will result in a good experience.  I think it'd be better to turn off auto-suggestions, and let Tab continue to do completion.

I'd recommend starting at the [Getting Started](https://chrisant996.github.io/clink/clink.html#getting-started) section of the documentation.  It quickly gets to a part about customizing key bindings, and there's a lot of other useful info there as well.

**Comment by Mqxx** [comment] 2023-12-20 09:08
Thanks for the support! I'll have a look at this.

**Comment by Mqxx** [comment] 2023-12-20 09:23
I have looked at the possible [keybindings](https://chrisant996.github.io/clink/clink.html#gettingstarted_keybindings) in the documentation, but I have not found a setting where I can change the whole thing for auto-suggest... As far as I have seen, it is permanently bound to <kbd>arrow right</kbd>. The only thing I have seen that I can customize is the keybind for completion.

**Comment by chrisant996** [comment] 2023-12-20 09:57
> I wouldn't necessarily say that... In every modern IDE or in other command lines, TAB is used as a keybind for accepting suggestions.

In all command shells, the Tab key performs what is known as "completion".

There are _**no**_ command shells where Tab performs the behavior associated with the gray text in the Clink "auto-suggestions" feature.

The auto-suggestions feature in Clink is the same as the auto-suggestions feature in the famous [fish shell](https://fishshell.com/).

> I have looked at the possible [keybindings](https://chrisant996.github.io/clink/clink.html#gettingstarted_keybindings) in the documentation, but I have not found a setting where I can change the whole thing for auto-suggest... 

[`clink-insert-suggested-line`](https://chrisant996.github.io/clink/clink.html#rlcmd-clink-insert-suggested-line)

```
"\t": clink-insert-suggested-line
```

> As far as I have seen, it is permanently bound to <kbd>arrow right</kbd>.

You said you want Tab to insert the suggestion.  That's totally possible; see above.

But did you mean to imply that you also want to make Right never insert the auto-suggestion text?  I'm not going to build that.  That would greatly complicate everything about the auto-suggestions feature.

I would recommend to completely turn off auto-suggestions, instead.  It is not intended to work how you're suggesting.  It is much, much less powerful/flexible than completions in general.  The main purpose of auto-suggestions is to offer the most recent command from the history matching what's been typed so far, or if there are no matches then offer the first possible completion.  It's a weak convenience:  you could access the most recent history entry with PgUp (or like I did, change your Up binding), and you could access the first completion by pressing Tab.

**Comment by Mqxx** [comment] 2023-12-20 10:36
> But did you mean to imply that you also want to make Right never insert the auto-suggestion text?

No

> [clink-insert-suggested-line](https://chrisant996.github.io/clink/clink.html#rlcmd-clink-insert-suggested-line)

Thanks this is what I was searching for.

**Comment by chrisant996** [comment] 2023-12-20 18:02
> Is there also a way to influence the behavior of [Popup Window](https://chrisant996.github.io/clink/clink.html#popupwindow)? For example, I want <kbd>Tab</kbd> to insert the currently highlighted item instead of <kbd>Enter</kbd> from the list.

The popup list key bindings are not configurable.

The documentation section on how they work covers the keys they recognize.

**Comment by chrisant996** [comment] 2023-12-20 18:48
> For example, in this scenario, I would think that I could select the selected suggestion with the arrow right. But it just selects the next item from the list. I mean yes if I had multiple items so that they would be displayed next to each other then it would make sense again, but if you only have a few items it is quite confusing. Especially if you are used to using an IDE.
> 
> ![image](https://private-user-images.githubusercontent.com/62719703/291846796-1b4feccc-a5b1-4f19-be26-19d8f3ec7d47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwOTc3MTAsIm5iZiI6MTcwMzA5NzQxMCwicGF0aCI6Ii82MjcxOTcwMy8yOTE4NDY3OTYtMWI0ZmVjY2MtYTViMS00ZjE5LWJlMjYtMTlkOGYzZWM3ZDQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDE4MzY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2NzE2M2Q4MzI0NGMyM2ZjNzM1NjY4MDE1NmUyMmEzMGIzNTc2ZTE3YzE3OTJhZmE0Yjg2ZjZkYjQzM2I2MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ho2SM2-AYK1bZ1d5tGpmleyVFimUt-SoDWuXktWX5-Q)

The `clink-select-complete` command has its own non-configurable key bindings.  The arrow keys are for navigating around the list.  If <kbd>Right</kbd> did something else instead of navigation, then either navigation wouldn't be possible, or the list would never be able to have more than 1 column.  Those aren't acceptable limitations.

Anyway, I understand your overall expectation.  I'm reluctant to introduce the requested behavior, because no command shells work that way currently.  And it's fundamentally incompatible with the `menu-complete` commands.  I think this is a case where the most effective solution is to adapt to how command shells work.

The auto-suggestion feature is the outlier.  If it's creating confusing or dissatisfaction, then turn it off.  Turning it off seems better than altering lots of other things to morph the auto-suggestion into a different kind of feature, where Tab inserts a displayed preview (in apps that do that, that's their only form of "completion"-like behavior, and they're riffing off of how completion has already worked for decades in command shells).

**Closed** 2023-12-23 19:42 UTC
Labels: duplicate, wontfix, question, working as intended

**Comment by peterhorsley** [comment] 2026-04-20 11:19
it's so confusing to see the gray text and then pressing tab and then some other command is applied.  i wanted this app to work, and tried to stick with it but it's just so annoying that it doesn't autocomplete the suggestions on tab.  accusing users of mixing up "auto-suggestions" versus "completions" is a mistake easily made when ur focus on the code - focus on the experience: they are the same thing.  sorry this app looked good but without proper tab key handling it's unusable.

**Comment by chrisant996** [comment] 2026-04-20 15:37
> it's so confusing to see the gray text and then pressing tab and then some other command is applied.  i wanted this app to work, and tried to stick with it but it's just so annoying that it doesn't autocomplete the suggestions on tab.  accusing users of mixing up "auto-suggestions" versus "completions" is a mistake easily made when ur focus on the code - focus on the experience: they are the same thing.  sorry this app looked good but without proper tab key handling it's unusable.  

@peterhorsley The first section of the documentation covers exactly this.

It's not completion at all, it's Suggestions.  I'm not trying to "accuse" anyone.  The fact is that there are two features, they compete with each other a bit, and the gray text is not connected to the completions feature.  I'm not saying that your expectations are unreasonable -- I'm only saying they are different from how the feature works.

You can turn it off very easily if you don't like the Suggestions feature.

Also have you tried the Suggestion List feature?  You can temporarily turn it on by pressing `F2`.  That might be more usable than the gray text suggestions.  If you want it on always, there's a setting to make it on by default.

Also, if you want the TAB key to insert the gray text, I can give you a little macro for that.  I don't think that's going to be very desirable, because the gray text comes from the suggestion engine, which show either a recent command or the first completion option available.  Connecting TAB to the gray text will make all of the other completion strings impossible to insert.  That will make the gray text feel more intuitive, but it will have a side effect of completely ruining the completion capabilities.  I'm happy to provide that, if you want to try it.

**Comment by chrisant996** [comment] 2026-04-20 16:21
> without proper tab key handling it's unusable

I hear your frustration.

The TAB key handling is the same as it always is in shells.

The only thing is that TAB works the same as it always does, _instead_ of inserting the gray text.  What's different is the gray text.

In the fish shell the gray text is on by default, and works the same as in Clink

In PowerShell the gray text is off by default, and works the same as in Clink.

I'm seriously considering turn off the gray text feature by default, because of the anger it seems to create when it's unexpected.

**Comment by chrisant996** [comment] 2026-04-20 17:04
@peterhorsley I want to be clear -- I'm very happy to make some kind of change here.

But I don't see any change that I could make that wouldn't overall cause more harm than good.  I'm happy to discuss some options with you, if you have suggestions.  Please understand that I might have to push back on some suggestions if there are side effects.

Maybe the best thing is to just turn off the gray text feature by default?  It's a very popular feature, and some people even say that the gray text is the only useful thing in Clink and without it they just wouldn't use Clink and they wouldn't be willing to have to turn it on manually.  And some people say the gray text is misleading and they won't turn it off manually and won't use Clink because it's on by default.  It's really hard to find an acceptable compromise between two such diametrically opposed viewpoints, but I would like to keep trying.

Also, personally, I never use the gray text anymore -- I always use the Suggestion List feature instead.  It removes the ambiguity about what TAB does, and it adds even more functionality overall.  You can press `F2` to try it, and if you like it then you could use `clink set suggestionlist.default true` to make it on by default.

I'm also considering making the gray text off by default, and just having a gray hint at the right side to mention about the `F2=Suggestion List` feature.

**Comment by peterhorsley** [comment] 2026-04-21 01:15
Thanks for your comments on this @chrisant996 and apologies my comment on this closed item was not courteous - i appreciate that tab-completion vs auto-suggestion are entirely separate features.  i tried to train myself to use the right-arrow key but muscle memory to press tab when seeing the gray auto-suggestion is too strong!  I would agree that the gray text is currently the most useful feature in Clink (although I haven't explored the full feature set yet).  Thanks for the suggestion to use F2 Suggest List feature, i'll try it.  

EDIT: I just installed latest and now see the command history shown automatically, really nice i like it!

**Comment by chrisant996** [comment] 2026-04-21 07:52
> I would agree that the gray text is currently the most useful feature in Clink (although I haven't explored the full feature set yet). 

This confuses me.  The gray text seems to be causing tremendous frustration.  If it's causing so much frustration, I don't understand how it's simultaneously considered the best feature in Clink.  Can you help me understand what's meant?

- Does it mean that the hundreds of other features in Clink haven't been noticed yet, because the gray text was so distracting and frustrating?  _(custom prompts, customizable key bindings, history engine, completion engine, input line coloring, custom scripts, and many other things)_
- Does it mean that everything in Clink is totally useless crap except for the gray text?  _(but the gray text is built upon both the history engine and the completion engine, which are a couple of major features in Clink, so that meaning would be even more confusing)_
- Does it mean the gray text feature is not causing frustration anymore and should stay as it is?  _(but if it causes such profound frustration then it seems like this can't be the meaning)_
- Does it mean the most important thing is for the shell to show a preview of how <kbd>Tab</kbd> will change the input line -- which would be a different feature that doesn't exist yet?  _(I hope not, because there are several cases where that seems impossible to do -- pressing <kbd>Tab</kbd> can cycle through available completions, and I don't see how to show an inline preview of what text will be deleted and also what text will replace it without creating even more confusion)_

Hopefully this helps clarify why I find it so confusing to hear that the gray text is so frustrating that it drives people to stop using Clink (without considering turning it off), but is also simultaneously considered to be the single best feature in the whole app.  I'm trying to genuinely listen and understand, to help me identify potential ways to improve the situation.  But I don't understand the feedback yet.  Maybe I'm taking the feedback too literally?

**Comment by chrisant996** [comment] 2026-04-23 09:55
The next update will include these changes:

1. **Breaking Change:** The "gray text" mode is off by default, but can be turned back on via `clink set autosuggest.inline true`.
2. When suggestions are available but the suggestion list isn't active, a right-aligned gray text hint will show up saying `[F2]=List Suggestions`.
3. The relevant documentation for how suggestions work is updated accordingly (this has been by far the most time consuming part of the changes).

**Comment by chrisant996** [comment] 2026-04-24 18:33
[v1.9.20](https://github.com/chrisant996/clink/releases/tag/v1.9.20) no longer shows inline suggestions by default (the "gray text").  It can be turned on if desired; it isn't removed, it's just not on by default anymore.  The Suggestion List is more powerful and less confusing, so it's the recommended way to use suggestions.  It can be toggled via <kbd>F2</kbd>, or it can be enabled by default via `clink set suggestionlist.default true`.  See docs for more details.
