### ISSUE TITLE
alt-. key binding for last argument does not work in vim terminal

### ISSUE THREAD

**Issue by eggbean** [chrisant996/clink#360] opened 2022-10-10 16:53 UTC
I use the `alt-.` shortcut a lot, but it doesn't work in vim's built-in terminal. When I start it it gives the clink startup message and everything else clink does seems to work, apart from this shortcut.

Instead of returning the last argument from the previous command it prints a literal `@` (at sign).

Clink and the gsudo command are life-savers when it comes to cmd.exe.

**Comment by chrisant996** [comment] 2022-10-10 19:26
Maybe vim is intercepting keystrokes.

What does "clink echo" and then Alt-. report as the keystroke?

**Comment by eggbean** [comment] 2022-10-10 22:02
Not sure if this is what you asked, but in vim terminal:

```
Microsoft Windows [Version 10.0.22621.730]
(c) Microsoft Corporation. All rights reserved.

Clink v1.3.46.d6fdd0
Copyright (c) 2012-2018 Martin Ridgers
Portions Copyright (c) 2020-2022 Christopher Antos
https://github.com/chrisant996/clink

C:\Users\jason>clink echo ®
Type a key to see its key sequence string.
Press Ctrl+C when finished.
```

**Comment by chrisant996** [comment] 2022-10-10 22:32
That's UTF8 input, and is not the code for Alt-. at all.

What locale and keyboard input language are you using in Windows?

Have you tried it outside of vim?

**Comment by eggbean** [comment] 2022-10-11 00:37
I was going to say UK English, but I checked:

```
C:\Users\jason>systeminfo
...
System Locale:             en-gb;English (United Kingdom)
Input Locale:              ru;Russian
Time Zone:                 (UTC+00:00) Dublin, Edinburgh, Lisbon, London
```
I did that some time ago when I read this:
https://krebsonsecurity.com/2021/05/try-this-one-weird-trick-russian-hackers-hate/

If that is the cause of this, this is the first time I have noticed any side-effect of having done so. I had forgotten all about it.

I don't remember how I did it and cannot see any way of reversing it. It doesn't matter though as I am planning on reinstalling Windows on this laptop some time soon anyway. Could this be the cause?

**Comment by chrisant996** [comment] 2022-10-11 01:25
> I don't remember how I did it and cannot see any way of reversing it. It doesn't matter though as I am planning on reinstalling Windows on this laptop some time soon anyway. Could this be the cause?

Uninstalling languages and keyboards is easy.  Settings > Time & Language > Language > Preferred languages.  Click on the language.  Click the Remove button.

> (Alt-. works fine with Clink outside vim terminal)

That makes it sound like the issue is vim terminal alters the incoming keystrokes (likely by accident).  Or maybe vim terminal is mishandling the input locale.

It's surprising that Russian would be the input locale for someone typing in English.  Perhaps the wrong input language is selected at the moment?

**Comment by chrisant996** [comment] 2022-10-15 19:33
Closing as "external".

**Closed by chrisant996** 2022-10-15 19:33 UTC
Labels: external

**Comment by eggbean** [comment] 2022-10-16 07:21
Thanks. I was going to reply once I had reinstalled Windows to see if the issue was resolved.

I do not remember who I changed the Input Locale, but everything remains the same apart from Russian being mentioned as being the Input Locale in systeminfo and possibly this issue in vim terminal. Russian does not appear anywhere in the Settings language section - not even in the Advanced keyboard settings where you can set 'Override for default input method`.

The reason that I somehow added the Russian input locale was because of the link I gave above. Once I reinstall Windows hopefully this issue with vim terminal will go away.

**Comment by eggbean** [comment] 2023-03-23 18:03
I have now reinstalled Windows but I still have this problem.

https://github.com/vim/vim/issues/12191#issuecomment-1481578540

**Comment by chrisant996** [comment] 2023-03-23 18:44
Reinstalling Windows would have no effect; this is a problem in how vim forwards keyboard input to an embedded terminal.  It's common for hosts of embedded terminals to have problems/bugs for some inputs (different hosts have different bugs for different inputs).

**Comment by eggbean** [comment] 2023-03-24 02:46
I suspected that it was caused by the Russian keyboard setting, but it clearly wasn't that.
