### ISSUE TITLE
cursor position is incorrect

### ISSUE THREAD

**Issue by kangarooxin** [chrisant996/clink#400] opened 2023-01-06 10:42 UTC
after upgrade to v1.4.7, the cursor position is incorrect, after type some word.

![image](https://user-images.githubusercontent.com/349092/210993299-bf666177-38ff-4fe0-a9aa-218af38f3a2d.png)

**Comment by chrisant996** [comment] 2023-01-06 15:12
I can help track down what's going on.

Can you please answer these troubleshooting questions?

- What version of Clink was being used before upgrading to v1.4.7?
- What is the output from running `chcp`?
- What is the output from running `set prompt`?

I'm curious why the prompt text is indented by 1 space.  That makes it seem like there's something unusual in the `%prompt%` environment variable.

Those are the first troubleshooting questions. I'll probably suggest more troubleshooting steps, depending on the answers.

**Comment by chrisant996** [comment] 2023-01-08 19:50
(@kangarooxin P.S. our of curiosity, what is the name of the font being used?  I like it and am curious if there's a Nerd Fonts version of it.)

**Comment by jtnord** [comment] 2023-01-09 13:55
I also see this.  upgraded from `1.4.3` IIRC.

happens for me when the text is towards the end of the line - and my prompt has delayed information so it is updated if that has any impact on things.

not so much that the cursor is incorrect - but that it also duplicated things.

e.g. in the following I have just typed `c` yet the auto complete looks like it is `ccls` which it is not
<img width="242" alt="image" src="https://user-images.githubusercontent.com/494726/211324278-50229de2-87a5-4f9e-9c33-f42f6f2121c4.png">

**Comment by jtnord** [comment] 2023-01-09 14:05
I was wrong about it only being related to long lines.

here is a result where I just typed `git status`

<img width="253" alt="image" src="https://user-images.githubusercontent.com/494726/211326416-6271cf08-fc52-48c0-9258-9d0019c97250.png">

**Comment by chrisant996** [comment] 2023-01-09 17:46
@jtnord can you share these?
- What is your prompt config? If you're using flexprompt, can you share your flexprompt_autoconfig.lua file?
- Can you share specific repro steps? Is it simply "type `git status`"?
- Can you confirm you're using v1.4.7?


P.S. v1.3.43 is the version where the input line display was rewritten, and v1.3.48 is the most recent update that included any fixes for the input line display routines.

P.P.S. The reason I asked the OP about `set prompt` is the prompt in the screen shot is very basic, and appeared to suggest it wasn't customized with Lua.

**Comment by tan-wei** [comment] 2023-01-10 08:59
Met the same issue.

**Comment by jtnord** [comment] 2023-01-10 10:36
> @jtnord can you share these?
> 
> * What is your prompt config? If you're using flexprompt, can you share your flexprompt_autoconfig.lua file?

<details><summary>` flexprompt_autoconfig.lua`</summary>
```
-- WARNING:  This file gets overwritten by the 'flexprompt configure' wizard!
--
-- If you want to make changes, consider copying the file to
-- 'flexprompt_config.lua' and editing that file instead.

flexprompt = flexprompt or {}
flexprompt.settings = flexprompt.settings or {}
flexprompt.settings.lines = "one"
flexprompt.settings.right_frame = "round"
flexprompt.settings.use_icons = true
flexprompt.settings.heads = "pointed"
flexprompt.settings.left_frame = "round"
flexprompt.settings.frame_color = "dark"
flexprompt.settings.flow = "concise"
flexprompt.settings.right_prompt = "{overtype}{exit}{duration}{time:format=%H:%M:%S}"
flexprompt.settings.spacing = "normal"
flexprompt.settings.powerline_font = true
flexprompt.settings.tails = "flat"
flexprompt.settings.use_8bit_color = true
flexprompt.settings.separators = "pointed"
flexprompt.settings.left_prompt = "{battery}{histlabel}{cwd}{k8s}{git}"
flexprompt.settings.style = "classic"
flexprompt.settings.charset = "unicode"
flexprompt.settings.symbols =
{
    prompt =
    {
        ">",
        winterminal = "â¯",
    },
}
```
</details>

> * Can you share specific repro steps? Is it simply "type `git status`"?

no, it seems to happen randomly - ie there is some trigger and then once in that state it seems to be somewhat sticky.

typing any command that offers completion suggestions inline will then trigger it.

(FWIW the resize redraw of the prompt issue is also back - possible related?)

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/494726/211528668-17770990-74e7-451c-970d-d057205a6fea.png">

> * Can you confirm you're using v1.4.7?

yes

> P.S. v1.3.43 is the version where the input line display was rewritten, and v1.3.48 is the most recent update that included any fixes for the input line display routines.

I could have been that version.  I'm kind of going from a fuzzy memory.  when I cam back after the Christmas/new year break I accepted the clink upgrade offer.  I am not fully sure if clink was offering me an upgrade before this or not...

let me see if I can find some history in the event log.

> 
> P.P.S. The reason I asked the OP about `set prompt` is the prompt in the screen shot is very basic, and appeared to suggest it wasn't customized with Lua.

**Comment by jtnord** [comment] 2023-01-10 10:59
So the following can repoduce it fairly well for me.

1. start terminal with a cmd.exe prompt
1. cd  to a location with a git clone (so we have the delayed git prompt expansion)
1. type `git status`  (this works)
1. type `git st`  (this is there things get messy)

![image](https://user-images.githubusercontent.com/494726/211533874-ca7faf57-245f-47c4-b8b9-53a532391dbb.png)

**Comment by chrisant996** [comment] 2023-01-10 18:48
> (FWIW the resize redraw of the prompt issue #320 is also somewhat back - possible related?)
> 
> <img alt="image" width="1094" src="https://user-images.githubusercontent.com/494726/211528668-17770990-74e7-451c-970d-d057205a6fea.png">

If you turn off the right-side prompt, then the resize issue will almost completely go away.

It is _**impossible**_ for any console mode program to support console resizes correctly.  Because the OS continues rearranging the screen _**while**_ the program is responding to the previous time the OS rearranged the screen.  The OS doesn't wait for the console mode program to respond to the resize; the OS just keeps resizing.  So the console mode program (in this case Clink) is trying to write to the screen, but the OS is rearranging the screen _**and moving the text cursor position**_ out from under the console mode program, while the program is using it (and relying on it).

Clink now performs the entire screen write in a single operation.  There is nothing further that Clink can do to improve upon that.  Any resize issues that still remain are entirely caused by the OS, at this point.

You'll notice that `git-bash` doesn't suffer from this problem.  But it's because the mintty console does not resize on the fly -- you can resize the window, but until you release the mouse, it doesn't rearrange the contents within the window.

You can achieve the same thing in normal Windows consoles, by turning off the "Show window contents while dragging" checkbox in Windows:  Settings > System > About > Advanced system settings > Settings... (in the "Performance box") > Visual Effects > Custom: > Show window contents while dragging.

**Comment by chrisant996** [comment] 2023-01-10 19:16
@jtnord Also, from close inspection of the screenshots you shared, I think that there is likely some additional flexprompt configuration in some other custom Lua script besides flexprompt_autoconfig.lua.

In addition to the `debug.log_terminal` stuff from my previous reply, can you also share all of the custom Lua scripts that apply flexprompt configuration?

(When I use the cited flexprompt_autoconfig.lua script with the DejaVuSansMono NF font, then on my screen the Kubernetes icon is different than in the screenshots, even though we're using the same font.  So this could indeed be an issue where certain icons being used are in the color emoji range, but get handled by the current font instead of by Windows Terminal.  Which is why it's so hard to "properly" support color emoji -- there is no standard yet, and the typical approaches used by terminal hosts interfere with console programs that need to control the cursor position, e.g. as part of an input line editor.)

**Comment by kangarooxin** [comment] 2023-01-11 09:40
> @kangarooxin I can help track down what's going on.
> 
> Can you please answer these troubleshooting questions?
> 
> * What version of Clink was being used before upgrading to v1.4.7?
> * What is the output from running `chcp`?
> * What is the output from running `set prompt`?
> 
> I'm curious why the prompt text is indented by 1 space. That makes it seem like there's something unusual in the `%prompt%` environment variable.
> 
> Those are the first troubleshooting questions. I'll probably suggest more troubleshooting steps, depending on the answers.

I use it in [tabby](https://github.com/Eugeny/tabby)，tabby updated bundled clink version on version Alpha 188，then it happend. 
Font is `JetBrains Mono Thin`.

**Comment by jtnord** [comment] 2023-01-11 10:17
[clink.log](https://github.com/chrisant996/clink/files/10391210/clink.log)

<img width="760" alt="image" src="https://user-images.githubusercontent.com/494726/211780158-11a8b043-9870-4588-9536-0a106a8bb7f7.png">

in this case I typed `dir` the first red `d` is spurious

**Comment by jtnord** [comment] 2023-01-11 10:52
[scripts.zip](https://github.com/chrisant996/clink/files/10391471/scripts.zip)

I also have scripts for completions from [vladimir-kotikov/clink-completions `commit:4517b653034f9c0e064c3c284df9182f0534ffbe`](https://github.com/vladimir-kotikov/clink-completions/tree/4517b653034f9c0e064c3c284df9182f0534ffbe)

**Comment by jtnord** [comment] 2023-01-11 10:54
> Also, I wonder if running clink set terminal.color_emoji one might make the problem stop occurring.

nope :-(

**Comment by chrisant996** [comment] 2023-01-11 18:37
> [clink.log](https://github.com/chrisant996/clink/files/10391210/clink.log)
> 
> <img alt="image" width="760" src="https://user-images.githubusercontent.com/494726/211780158-11a8b043-9870-4588-9536-0a106a8bb7f7.png">
> 
> in this case I typed `dir` the first red `d` is spurious

@jtnord Thank you for capturing and sharing the log.

Replaying the log reproduces the problem locally for me.

I'm investigating it now...

**Comment by chrisant996** [comment] 2023-01-11 20:18
@jtnord The log helped identify what's happening, thanks.

## What's happening

The issue is triggered by line 30 of the `flexprompt_k8s.lua` script, i.e. the ☸ symbol in the Kubernetes prompt module.  And when I use that script, then I'm able to reproduce the problem.

The symbol ☸ is in the color emoji range: it is 0x2638, which is listed in [Unicode Emoji Data Files](https://www.unicode.org/reports/tr51/#emoji_data) in the `emoji-test.txt` file.  According to the Unicode v15.0 specification, the expectation is for it to be rendered using two character cells.

But the combination of Windows Terminal and your font ends up rendering it using the font instead of as a color emoji, and it shows up as a single-width character instead.  And strangely, on my computer Windows Terminal renders it as an actual _color emoji_, but shrinks the size to be half a character cell tall, and one character cell wide.  But for some other color emojis it renders them as a full character cell tall, and two character cells wide.  This is just craziness, from the perspective of any console mode program.

That's also why there are two spaces between the prompt and the input text, instead of the expected one space.  The input line begins at the cursor position calculated from the widths of the characters in the prompt text.  Since that width is one cell greater than the rendered width, the cursor position ends up an extra space to the right.

And the reason the input line gets garbled is because somewhere in the code there's a case where it prints the prompt followed by the input text, but misses setting the cursor position in between those.  Normally it prints the prompt, then forcibly sets the cursor position to the calculated column position, then prints the input text.

And the reason `clink set terminal.color_emoji one` didn't fix the issue is because of two things:
1. The possible values are `on`, `off`, and `auto`.  Neither `one` nor `two` are possible values.  The `one` gets interpreted as `on` -- and I'll fix that misinterpretation.
2. Even using `clink set terminal.color_emoji off` doesn't fix the issue, because it accidentally only takes effect in new Clink sessions -- and I'll fix it to take effect immediately.

# Good news and bad news

**The good news** is that I just have to track down where it's printing the prompt immediately followed by the input line, without positioning the cursor in between.  Fixing that to force the cursor position should solve the glitched display.

**The bad news** is that there's nothing I can do to "fix" the inaccurate measurements themselves.  That's an issue between the OS and the terminal program and the font.

The font affects how the symbol is rendered:
- I've tried about 10 fonts, and haven't yet found one that renders the symbol as a full size color emoji.  But I've found other disappointing stuff:
- With JetBrains Mono, the symbol is drawn as a miniature color emoji:
  ![image](https://user-images.githubusercontent.com/17440311/211903081-c03ff894-ceb6-4c72-bb4a-a0581b1e7e28.png)
- With DejaVuSans Mono, the symbol is drawn as a font character:
  ![image](https://user-images.githubusercontent.com/17440311/211903311-5d31f396-0979-44a6-a0ec-d1f76ef03e37.png)
- But Lucida Console renders that symbol as a miniature color emoji ... but renders another symbol as a full size double-width color emoji:
  ![image](https://user-images.githubusercontent.com/17440311/211904550-6d701444-685d-4106-a7f7-16cd82366c1c.png)

These are unpredictable behaviors, from the perspective of a console mode program.  😭

Ultimately using fancy symbols is always going to be fiddly and error prone, because the software industry doesn't have a standard yet for how it should actually work, and the closest thing to a standard that exists is the Linux `$TERM` stuff which is inherently fiddly and error prone and puts the responsibility entirely on the individual user for configuring their system so that the OS + font + each individual terminal program are all configured in compatible ways.

Not a great situation, but at least Clink v1.4.8 will make the intermittent glitching stop.

**Comment by chrisant996** [comment] 2023-01-11 22:26
Fixes have been made, to the extent that it is possible to do so.

However, there is a case that can't be fixed:  if the line reaches the right margin, then line wrapping can be affected and happen inaccurately.  Since there's no way for Clink (or any console mode program) to know how the terminal is _actually_ rendering the text, there is no way for Clink to tell whether line wrapping is really occurring.  Which means there's no way to position the cursor correctly if an arithmetic mismatch coincides with the right margin.

When that case occurs, then the input line display gets garbled and "eats" lines.  That is an external problem that lies in the (lack of) communication between the OS, the terminal program, and the current font.  Unfortunately Clink can't do anything about that.  Users will have to choose different fonts or terminal programs, or make use of different symbol characters.

**Comment by chrisant996** [comment] 2023-01-11 23:53
There are also flaws in the way I was using the Color Emoji data table.
- It turns out _**NOT**_ everything in the color emoji table is actually a color emoji.  I'll filter them out of the table.
- It turns out _**SOME**_ things in the color emoji table are expected to be rendered as single width normal characters, and not as emoji at all.  I'll filter them out of the table.
- It turns out some sequences are ambiguous how wide they will be, in which case it is completely up to the software rendering the emoji.  There's no way for Clink to predict reliably how wide they'll be.  I'll filter them out of the table.

Emoji can be sequences of various characters chained together.  Some combinations are meant to behave differently together than alone.  It turns out Windows Terminal (and possibly the DirectX APIs for drawing color emoji) seem to be not fully up to date with the Unicode v15.0 spec, and thus for example 🏴󠁧󠁢󠁥󠁮󠁧󠁿 gets rendered as the emoji followed by a bunch of boxes.  That's happening inside Windows Terminal -- Clink thinks the sequence of bytes should be rendered as a single color emoji that shows up as double-width, but Windows Terminal is drawing the double-width color emoji followed by an additional 6 box characters that should not be displayed, according to the Unicode spec.

Hopefully it's becoming clear why this is a mess, and why Clink is very limited in what it can do to try to compensate for problems in the OS and terminal programs and fonts.  😞

**The simple answer is "choose different symbols to use, which don't get mishandled, regardless of whether the mishandling happens in Clink or the OS or the terminal program or the font.**

**Comment by chrisant996** [comment] 2023-01-12 00:07
I'm adding a troubleshooting feature to the <kbd>Ctrl</kbd>-<kbd>X</kbd>,<kbd>Ctrl</kbd>-<kbd>Z</kbd> diagnostic output:  it will analyze the prompt string to try to detect characters that have a high chance of having width computation problems, and it will report them.

That will at least make it a little easier to identify what's going on without necessarily needing me to spend hours investigating individual cases.

**Comment by chrisant996** [comment] 2023-01-12 02:54
@kangarooxin Can you try upgrading to Clink v1.4.8?

The information jtnord shared helped track down some issues, and v1.4.8 will probably fix the problem you encountered.

However, I installed tabby and cannot reproduce the problem in the screenshot that you shared.
So, if you still encounter a problem after upgrading to 1.4.8, then please do these steps:

1.  Run `clink set debug.log_terminal true`
2.  Start a new tab in tabby
3.  Make the problem happen
4.  Upload the `clink.log` file here (you can run `clink info` to find where the log file is).

**Comment by chrisant996** [comment] 2023-01-12 02:57
@jtnord Can you try upgrading to v1.4.8? It should fix all of the issues you encountered, and you should be able to continue using the same k8s symbol without issues.

(Except for the terminal resizing problem, since that's an OS issue and there's nothing Clink can do about it; [details here](https://github.com/chrisant996/clink/issues/400#issuecomment-1377699942) in case that reply got lost.  That reply shares a way to solve the resize problems, but it also affects all other window resizing as well.)

**Comment by chrisant996** [comment] 2023-01-12 03:30
It also looks like Clink v1.4.8 may have solved Cmder's problems with the lambda character in the prompt (at least when using CMD -- but of course not when using bash or powershell or etc).

**Comment by chrisant996** [comment] 2023-01-12 04:32
Yay!  Clink v1.4.9 fixes the Cmder lambda problems for CMD.exe (of course not for bash or powershell or etc, though).

**Comment by jtnord** [comment] 2023-01-17 10:31
> * It turns out _**NOT**_ everything in the color emoji table is actually a color emoji.  I'll filter them out of the table.

Ahh yes.  There are modifiers that can also change this on the fly :-) (Fitzpatrik tonal rang colour for the faces and the colour/non color for things like my k8s icon and 🗺️ / 🗺 - GH may be messing with me here - but see `FE0E` and `FE0F` [modifiers](https://www.unicode.org/charts/PDF/UFE00.pdf)!)

I guess you already know all this :-) 

updated to ` v1.4.11.088f68` and so far it seems to work!
Thanks again

**Comment by chrisant996** [comment] 2023-01-17 16:43
@jtnord yep, here are the data files Clink uses for this.

Official Unicode data file for emoji:
https://github.com/chrisant996/clink/blob/master/clink/terminal/src/emoji-test.txt

Subset that Clink ignores because Readline can't handle multi-character sequences for determining width:
https://github.com/chrisant996/clink/blob/master/clink/terminal/src/emoji-filter.txt

Rewriting Readline to support that would be a major work item and introduce heavy churn into the Readline code base. That's not something I'm willing to take on.

**Comment by kangarooxin** [comment] 2023-01-18 02:08
> i has updated to v1.4.11

![image](https://user-images.githubusercontent.com/349092/213064188-e26fd5cb-5f84-4b84-83d7-0ef82cf99aa2.png)


[clink.log](https://github.com/chrisant996/clink/files/10441193/clink.log)

**Comment by chrisant996** [comment] 2023-01-19 02:01
@kangarooxin that log file shows that the cursor position repeatedly mysteriously shifts by one space _**without Clink doing anything**_.

Which makes sense, since you're using Tabby.  While investigating #406, I did a bunch of testing with Tabby.  Tabby is broken with CJK codepages -- it moves the cursor position incorrectly very often.  The buggy behavior occurs with both "CMD (stock)" profile and "CMD (clink)" profile; it's not a Clink issue, and the problem doesn't occur with other terminal programs.

In the screenshot, Tabby is using JetBrainsMono to draw the text.  But the OS may think the font is something else, and one or more of the characters might be double-width in the other font.  In my testing, that is the situation where Tabby malfunctions.

Can you try this pre-release version of Clink and then share the resulting log file?
This pre-release version has additional logging that includes the name of the font the OS thinks will be used.
[clink.1.4.12.2e12e2.zip](https://github.com/chrisant996/clink/files/10452762/clink.1.4.12.2e12e2.zip)
You can extract the .zip into the Tabby\resources\extras\clink directory.

(This pre-release version is a "release candidate" -- I currently anticipate that it will be released as an official update soon.)

**Comment by chrisant996** [comment] 2023-01-25 21:28
The issue that @kangarooxin ran into is a bug in Tabby.  I can reproduce the problem in Tabby, I did extensive debugging to verify that Tabby internally gets confused about the cursor position, and no other terminal hosts encounter the problem.

Tabby gets confused about the cursor position in CJK code pages.  It shows the cursor in one place but outputs text at a different place.  It also may get confused about how to process the `ESC [` _`n`_ `G` escape code in CJK code pages.

Clink can't fix this or work around it; only Tabby can fix it.

**Closed by chrisant996** 2023-01-25 21:28 UTC
Labels: external
