### ISSUE TITLE
Paste on mouse right click duplicates second character

### ISSUE THREAD

**Issue by cwacha** [chrisant996/clink#352] opened 2022-09-27 21:44 UTC
I often select text in cmd and then right click it to add it to the clipboard. Then I paste it using another right click into the commandline.
In regular cmd (without clink) it always works as expected. But I noticed in version 1.3.43.404306 that the following action leads to a weird result:

Action:
- type `cd ` (cd followed by space) into commandline
- select path or other text from history, then right click to add it to clipboard (example: `C:\Windows\System32`)
- paste it with right click
- Outcome: `cd C::\Windows\System32` (notice the duplicated colon, second character of paste)

Expected: 
- Outcome: `cd C:\Windows\System32`

The strange thing is this does not happen all the time. But it is reproducible with the exact procedure described above. 
Note:
- a consecutive paste using right click shows the pasted text correct without duplication. 

I am using the following inputrc (copy pasted from your documentation):

```
# Some common Readline config settings.

set colored-stats                 on   # Turn on completion colors.
set colored-completion-prefix     on   # Color the typed completion prefix.

# Some config settings that only work in Clink.

$if clink
set search-ignore-case            on   # Case insensitive history searches.
set completion-auto-query-items   on   # Prompt before showing completions if they'll exceed half the screen.
$endif

# Add your keybindings here...

```

I have not made any other changes. 

### Environment
I am using
- Windows 11
- Windows Terminal 1.14
- cmd.exe 10.0.22000.1
- clink 1.3.43.404306
- (when I open cmd.exe via start menu it opens directly inside Windows Terminal)

**Comment by chrisant996** [comment] 2022-09-27 22:24
Duplicate of #348.  Fix was released yesterday.

**Closed by chrisant996** 2022-09-27 22:24 UTC
Labels: duplicate
