### ISSUE TITLE
cmd is displayed with incorrect width for prompt in vscode 

### ISSUE THREAD

**Issue by NewUserHa** [chrisant996/clink#690] opened 2024-10-18 22:43 UTC
![image](https://github.com/user-attachments/assets/bca92cdf-cdd3-4375-a9db-77b8aa499747)
![image](https://github.com/user-attachments/assets/e075755d-4905-4352-a8a7-d6c70a946695)

in vscode,
* neither the default left pannel opened or closed helps to fix the issue; 
* without `clink config set prompt oh-my-posh`, for [clink-flex-prompt](https://github.com/chrisant996/clink-flex-prompt) this issue exists as well

additional, no matter in standalone cmd or in vscode, after the width of the cmd window, it needs to input multiple extra line for clink to restore to the correct width for prompt

**Comment by chrisant996** [comment] 2024-10-19 01:44
It looks like you're using oh-my-posh.

Oh-my-posh is doing all of the width measurements and construction of the prompt. 

Clink is not involved at all.

Report it in the oh-my-posh repo.

**Comment by chrisant996** [comment] 2024-10-19 01:48
I see that you said it happens for both oh-my-posh and clink-flex-prompt.

The programs are using the OS console API to ask the console what its width is.

The console is reporting a different width than its actual width.  That seems like a problem in VSCode's console implementation.  Search for related issues in the VSCode repo, and report it there.

I vaguely recall there might be a known issue in VSCode.

**Comment by chrisant996** [comment] 2024-10-20 14:18
@NewUserHa Also, it looks like your prompt is using some icon characters which are not present in the font you're using.  That can interfere with programs' ability to measure the width of characters.

Also, it looks like your system code page might have trouble with [East Asian Ambiguous Width](https://www.unicode.org/reports/tr11-4/) characters in the Unicode standard, and some of the Nerd Fonts icons are located in that Unicode range.  Try pressing `Ctrl-X``Ctrl-Z` and check whether any problematic characters are detected in the prompt string.

Also, VSCode might have trouble rendering some icon characters.  Windows Terminal has the most complete rendering capabilities at this time.  Most other terminal programs on Windows have problems with various icon characters, and especially Unicode surrogate pairs.

You might need to change the code page, or change the font to a Nerd Fonts v3 font with all the icons, or configure the prompt to not use icon characters (or different icon characters.

(Note:  I've tried to be careful to make clink-flex-prompt not use surrogate pairs for icons or ambiguous width icons -- but if you aren't using the latest clink-flex-prompt, then you might need to update your clink-flex-prompt repo.)

**Comment by chrisant996** [comment] 2024-10-20 14:21
Also, I am not able to reproduce the problem you've described.

![image](https://github.com/user-attachments/assets/10a2104a-0978-462b-86bb-ddd3a3130fb7)

**Comment by NewUserHa** [comment] 2024-10-21 17:32
no icon looks having display issue in the original picture.
`chcp 65001` the issue still exists.
`Ctrl-X ` ` Ctrl-Z` and `Ctrl-X Ctrl-Z` all look no issue.
Fonts and clink-flex-prompt both are latest version.

should create a issue at vscode?

**Comment by chrisant996** [comment] 2024-10-21 19:19
> no icon looks having display issue in the original picture.

Why do you say there are no icons in the original picture?

The original pictures all have multiple icons shown.  And at least one of them is clearly broken (empty square).

> Fonts and clink-flex-prompt both are latest version.
> 
> should create a issue at vscode?

Probably, unless it's a font problem or surrogate pair issue -- which you have not taken steps to rule out yet.

If you create an issue at VSCode, then you need to say that oh-my-posh encounters the problem (because it does -- and that's completely unrelated to Clink, and is much easier to use for reproducing the issue).

**Comment by NewUserHa** [comment] 2024-10-21 20:32
> The original pictures all have multiple icons shown. And at least one of them is clearly broken (empty square).

that does have a square, however both Fonts and clink-flex-prompt latest version and chcp is already 65001. so it perhaps is issue from that theme

> then you need to say that oh-my-posh encounters the problem

`oh-my-posh print primary` can reproduce the issue without clink indeed, via tested with `noclink`.

**Comment by chrisant996** [comment] 2024-10-21 21:14
> that does have a square, however both Fonts and clink-flex-prompt latest version and chcp is already 65001. so it perhaps is issue from that theme

You haven't shared what oh-my-posh theme you're using.

_**If**_ it uses any icons that use Unicode Surrogate Pairs (look up what that means), then the widths will be incorrect in conhost and conemu and probably in VSCode.  Because those only support UCS2, which is a precursor to Unicode.  Windows Terminal supports full Unicode, including Surrogate Pairs.

And it's possible that the cause of the problem you're experiencing is something else.

Anyway, regardless of what is the cause, the issue occurs without Clink and clearly has nothing to do with Clink.

I'm closing the issue.

**Closed** 2024-10-21 21:14 UTC
Labels: external

**Comment by NewUserHa** [comment] 2024-10-21 22:14
the oh-my-posh theme is "chips".  

in vscode, other themes other than the default "dracula" theme eg "night-owl" "atomic" have this issue as well. the looking of this width issue looks similar to its looking in cmd without chcp 65001 but chcp 65001 in vscode doesn't fix it.
while at the same time, in vscode the oh-my-posh default theme "dracula" has wrong position with with the cursor during auto-suggestion function (also exists if chcp 65001)
![image](https://github.com/user-attachments/assets/ddfa75b9-c4cb-46f6-802d-e809875bf754)

**Comment by chrisant996** [comment] 2024-10-22 00:31
> the oh-my-posh theme is "chips".  
> 
> in vscode, other themes other than the default "dracula" theme eg "night-owl" "atomic" have this issue as well. the looking of this width issue looks similar to its looking in cmd without chcp 65001 but chcp 65001 in vscode doesn't fix it.
> while at the same time, in vscode the oh-my-posh default theme "dracula" has wrong position with with the cursor during auto-suggestion function (also exists if chcp 65001)
> ![image](https://github.com/user-attachments/assets/ddfa75b9-c4cb-46f6-802d-e809875bf754)

@NewUserHa none of that has anything to do with Clink.  I invite you to take the discussion to a different repository.

**Comment by NewUserHa** [comment] 2024-10-22 14:19
ok, thanks.
