### ISSUE TITLE
previous command becomes ‘[A’

### ISSUE THREAD

**Issue by simaek** [chrisant996/clink#112] opened 2021-05-07 10:39 UTC
Use the arrow keys to call up the previous command, strange characters will appear.
I haven't encountered this problem before. I only discovered it recently. It may be related to the update of windows. I tested it on a colleague's computer and another computer of mine, and it all reappeared.
Below is a screenshot.

![screen](https://user-images.githubusercontent.com/35521828/117438013-8dc43000-af63-11eb-81fd-ad8011a8d54c.gif)

It seems that the readline module has a few strange inputs.

**Comment by chrisant996** [comment] 2021-05-07 16:27
P.S. `[A` is part of the escape code produced by <kbd>Up</kbd>.  Somehow the initial escape character is missed.

Also, I'm not able to reproduce this, so can you share any additional information about the configuration or locale or etc?

Please share the clink.log file, too, if possible.

**Comment by simaek** [comment] 2021-05-07 16:54
Do you mean this file?
![image](https://user-images.githubusercontent.com/35521828/117482811-7bfc8000-af97-11eb-9879-6c3a3a22e9bf.png)

[inputrc.txt](https://github.com/chrisant996/clink/files/6443148/inputrc.txt)

I ran `clink echo`, and pressed the arrow keys and esc key, the results are as follows:

![image](https://user-images.githubusercontent.com/35521828/117482201-9eda6480-af96-11eb-9ffe-23592f75bd2e.png)

locale:
LANG=zh_CN.UTF-8
LC_CTYPE="zh_CN.UTF-8"
LC_NUMERIC="zh_CN.UTF-8"
LC_TIME="zh_CN.UTF-8"
LC_COLLATE="zh_CN.UTF-8"
LC_MONETARY="zh_CN.UTF-8"
LC_MESSAGES="zh_CN.UTF-8"
LC_ALL=

**Comment by chrisant996** [comment] 2021-05-07 17:09
If the inputrc file came from `/etc/` that doesn't seem like the one Clink is using.

Use `clink info` to find which inputrc file Clink is loading (and all the places it searches for them).

That's the one I need to see.  Maybe it's the same `/etc/` one, but that would be surprising since that isn't a directory that Clink searches unless specially configured to do so.

**Comment by simaek** [comment] 2021-05-07 17:27
![image](https://user-images.githubusercontent.com/35521828/117485669-3d68c480-af9b-11eb-9a7f-61aea06dca1a.png)
It seem that no inputrc files are configurated.

Steps:
1. type 'grep' press Enter
2. type `Up`, display `[A`

No more other steps.

It seems to appear only when using *NIX commands. e.g. `ls`, `cat`, `grep`. But when using CMD cammands, such as `dir`, it will activate the previous history entry correctly.

**Comment by chrisant996** [comment] 2021-05-07 18:01
Oh!  I understand now roughly what's happening, thanks to your use of `debug.log_terminal`:

1. type `grep`, press <kbd>Enter</kbd>
2. press <kbd>Up</kbd>, press <kbd>Enter</kbd>
3. press <kbd>Up</kbd>

Somehow the initial `\e` from the <kbd>Up</kbd> in step 3 is getting treated as separate input and getting reconverted into a separate press of <kbd>Esc</kbd>, so the `\e[A` gets translated into `\e[27;27~[A`.

Are you using WSL or cygwin in Cmder?  Or anything else other than simply launching cmd.exe?  It appears something is intercepting console input and forwarding it (inaccurately), causing Clink to sometimes see the real input stream but sometimes see a preprocessed simulated input stream.

This sounds very similar to this known issue in ConEmu:
[ConEmu #1691](https://github.com/Maximus5/ConEmu/issues/1691)
[Cmder #2488](https://github.com/cmderdev/cmder/issues/2488)

**Comment by chrisant996** [comment] 2021-05-07 18:07
One more question:  Does this happen with Clink in a standalone cmd.exe as well?  Or only inside Cmder/ConEmu?

**Comment by simaek** [comment] 2021-05-08 00:36
Yes, I am using cygwin in Cmder. This is the default startup task of Cmder.
I ran `cmd /k ""%ConEmuDir%\..\init.bat"` in the native cmd.exe to use Cmder, it did not happen.
You are right, this may caused by ConEmu.

**Comment by simaek** [comment] 2021-05-08 00:36
Yes, I am using cygwin in Cmder. This is the default startup task of Cmder.
I ran `cmd /k ""%ConEmuDir%\..\init.bat"` in the native cmd.exe to use Cmder, it did not happen.
You are right, this may caused by ConEmu.

**Comment by chrisant996** [comment] 2021-05-08 01:45
Ugh.  Ok, I will try to investigate inside ConEmu's source code and see if I can find more details and/or a workaround.  That might take a while, though.

**Comment by chrisant996** [comment] 2021-05-08 20:30
> It seems to appear only when using *NIX commands. e.g. `ls`, `cat`, `grep`. But when using CMD cammands, such as `dir`, it will activate the previous history entry correctly.

This part is very interesting.

- Where are the *nix commands coming from?  E.g. what *nix system do you have installed?
- How do you launch Cmder, and from where?  E.g. from the Start menu, or from a bash shell, or another way?

Maybe *nix commands are leaving the console mode set to an unexpected mode, or maybe some ConEmu internal state isn't restored after a *nix command.  If we can enable me to reproduce the issue, that will significantly improve the chances of successfully resolving this problem.

Thanks!

**Comment by chrisant996** [comment] 2021-05-08 21:57
Yay, I can repro now:

0. Not sure whether this was a necessary step, but I installed Windows Subsystem for Linux and installed Ubuntu.
1. <kbd>Win</kbd>+<kbd>R</kbd> and `c:\wbin\Cmder\Cmder.exe`
2. `ls`
3. <kbd>Up</kbd>

Investigating...

**Comment by chrisant996** [comment] 2021-05-08 22:36
It's the ConEmu "Terminal Mode".

You can observe the terminal mode change by doing this:
- Go to Status Bar in Settings (Settings > Features > Status bar).
- Make sure the "Show status bar" box is checked.
- Add the "Terminal modes" column to the Selected columns.
- Click "Save settings".

Normally there will be a "WK" in the status bar (hover over it to see a description).
When a cygwin program is launched, the terminal mode indicator changes to "XK" when the program is running, and changes back to "WK" about 5 seconds after the program finishes.

In the "XK" mode ConEmu intercepts all keyboard input and converts it to Xterm input.  That's what's interfering with Clink (and it will interfere with CMD.exe and some other programs, too).

**Comment by chrisant996** [comment] 2021-05-08 23:09
This is [ConEmu #2302](https://github.com/Maximus5/ConEmu/issues/2302) and is fixed in ConEmu 210422.

Cmder currently includes ConEmu 210304.

I confirmed that I can't reproduce the problem in the latest ConEmu -- the terminal mode switches back to Windows ("WK") immediately.  The issue was affecting Far and other programs, too.

**Closed** 2021-05-08 23:11 UTC
Labels: external

**Comment by lilixiong2018** [comment] 2025-02-11 03:26
Here is my version:
Microsoft Windows [Version 10.0.18363.418]
ConEmu 230724 (Stable).
Clink 1.7.10.e3c993
zoxide 0.9.6
clink-zoxide from https://github.com/shunsambongi/clink-zoxide

I have been using cmder v1.3.25 (directly using cmd as the shell) for a long time, but I never encountered this issue until recently when I downloaded zoxide from https://github.com/ajeetdsouza/zoxide/releases and clink-zoxide
from https://github.com/shunsambongi/clink-zoxide and added them to cmder. Since then, I have frequently encountered the following problems:
1) When I press the up arrow, it displays ]A, and when I press the right arrow, it displays ]C.
2) When I copy a file path from the file manager (e.g., G:\svnproj\leanote\tools\widdler\webcontent), the command prompt shows something like cd /g/svnproj/leanote/tools/widdler/webcontent.

Moreover, both of these issues occur randomly (not frequently, but several times a day, causing some inconvenience).
I am not sure whether it is a problem with ConEmu, clink, or clink-zoxide, or if it is due to some configuration issue.

λ clink info
version  : 1.7.10.e3c993
session  : 12564
injected : clink_dll_x64.dll
binaries : G:\cmder\vendor\clink
state    : G:\cmder\config
log      : G:\cmder\config\clink.log
settings : G:\cmder\config\clink_settings
history  : G:\cmder\config\clink_history
scripts  : G:\cmder\vendor ; G:\cmder\vendor\clink ; G:\cmder\config
inputrc  : %clink_inputrc%
             (unset)
         : state directory
             G:\cmder\config\.inputrc
             G:\cmder\config\_inputrc
         : %userprofile%
             C:\Users\Administrator\.inputrc
             C:\Users\Administrator\_inputrc
         : %localappdata%
             C:\Users\Administrator\AppData\Local\.inputrc
             C:\Users\Administrator\AppData\Local\_inputrc
         : %appdata%
             C:\Users\Administrator\AppData\Roaming\.inputrc
             C:\Users\Administrator\AppData\Roaming\_inputrc
         : %home%
             C:\Users\Administrator\.inputrc
             C:\Users\Administrator\_inputrc
system   : 10.0.18363.418
codepage : 936
keyboard langid : 2052
keyboard layout : 00000804

**Comment by chrisant996** [comment] 2025-02-11 03:47
@lilixiong2018 I moved your comment to a new issue, so that it can be tracked properly.
