### ISSUE TITLE
My attempt at some sort of feedback after ~9 days

### ISSUE THREAD

**Issue by garoto** [chrisant996/clink#13] opened 2020-10-30 20:25 UTC
And I've been collecting notes about the behavior of the program since, but the bottomline is that it "works great!" and is already in its current state, a huge improvement and an excellent replacement over the v0.4.9 that I was using (n.b.: never really used martin's v1.0.x more than a few hours back in the day).

With that said, I find it hard to give proper bug reports since you're commiting every day constantly, so instead of sitting on these shitty notes/bugs I made, I'll just dump them below in no particular order and hope they might be useful to you somehow:

```
Potential Bugs:
* alt+<n> followed by alt+ctrl+y isn't working
* arrow keys don't exit `reverse-search-history` like in bash (need to press ctrl+j)
* `history <n>` returns errorlevel 1?
* doskey macros separated by a `$T` echoes the next cmdline
* doskey macros beggining with `$T` are not recognized as valid command (works in vanilla cmd.exe)
* alt+home behavior is inconsistent (only works after alt+up is performed and then stops working)
* `clink history delete <n>` returns a CRT error on my Win8.1:
	---------------------------
	Microsoft Visual C++ Runtime Library
	---------------------------
	Assertion failed!

	Program: C:\Apps\Diversos\Clink\clink_dll_x64.dll
	File: C:\repos\clink\clink\app\src\history\history_db.cpp
	Line: 757

	Expression: false

	For information on how your program can cause an assertion
	failure, see the Visual C++ documentation on asserts

	(Press Retry to debug the application - JIT must be enabled)
	---------------------------
	Abort   Retry   Ignore   
	---------------------------
```

I have a few feature requests as well, but I'll leave those to a separate issue (that is, if you're willing to deal with (mostly cosmetic) requests at this point).

**Comment by chrisant996** [comment] 2020-11-03 13:07
> And I've been collecting notes about the behavior of the program since, but the bottomline is that it "works great!" and is already in its current state, a huge improvement and an excellent replacement over the v0.4.9 that I was using (n.b.: never really used martin's v1.0.x more than a few hours back in the day).

Glad to hear it.  There are still a few lingering issues that need better long term solutions, and I need to finish documenting the Lua API (I've made lots of progress recently!).  Then I'll need to update the scripts from the clink-completions repo, and work with the cmder team to get cmder and the new clink working together.

Then I'll probably go into maintenance mode for a bit, before circling back to tackle some of the more ambitious stuff like CUA selection mode (Shift+Arrow keys to select like in edit controls, etc).

> With that said, I find it hard to give proper bug reports since you're commiting every day constantly, so instead of sitting on these shitty notes/bugs I made, I'll just dump them below in no particular order and hope they might be useful to you somehow:

This is great, thank you!  I'll look at them deeper when I get a chance.  In the meantime, here are some quick responses:

> * alt+home behavior is inconsistent (only works after alt+up is performed and then stops working)

Oops, fixed.

> * doskey macros separated by a `$T` echoes the next cmdline

Thanks, yeah, it's not working quite right.

> * arrow keys don't exit `reverse-search-history` like in bash (need to press ctrl+j)

Thanks, I'll look into that.  The big picture issue is that Readline's key binding system allows gibberish to be input accidentally if you press an extended key that isn't bound to anything.  I know that's how *nix terminals work, but I considered it unacceptable in the late 80's, and I still do, so I've made Clink's input system smarter -- if a particular extended key isn't bound, then Clink will avoid sending the key sequence through the terminal input.  However, Readline has input modes where it isn't really using the key bindings in the first place, and I don't have the conditions quite right yet for which keys to suppress in those input modes.

> * alt+< n > followed by alt+ctrl+y isn't working
> * `history <n>` returns errorlevel 1?
> * doskey macros beggining with `$T` are not recognized as valid command (works in vanilla cmd.exe)

Great, I'll look into these, thanks.  I can reproduce them but I'm not sure offhand what's going on for them.

> * `clink history delete <n>` returns a CRT error on my Win8.1:

Thank you -- I can reproduce it.  It's probably for the best that it isn't working at the moment, because the new `history.max_lines` limiter needs to not run by default in `clink history` (otherwise it can change the <n> index and the invoked command may operate on a different line than was intended).  Also there probably should be something like a `clink history limit` command to explicitly force the limiter to run.

> I have a few feature requests as well, but I'll leave those to a separate issue (that is, if you're willing to deal with (mostly cosmetic) requests at this point).

Yes, please file issue(s) for them.  Thanks!

**Comment by chrisant996** [comment] 2020-11-04 03:27
3 of the bugs from the original post are fixed, and the rest have been promoted into separate issues.  So I'll close this one.

**Closed by chrisant996** 2020-11-04 03:27 UTC
Labels: bug
