### ISSUE TITLE
No such file or directory; failed to install file 'themes\'.

### ISSUE THREAD

**Issue by MagicAndre1981** [chrisant996/clink#681] opened 2024-10-13 20:24 UTC
I made the update to from 1.6.21 to  1.7.0 and saw the message during update:

```
C:\WINDOWS\system32>clink update
Checking latest version...
Downloading latest release v1.7.0...
Expanding zip file...
No such file or directory; failed to install file 'themes\'.
```

Update worked, I'm now at 1.7.0, but I'm a bit confused by this message.

**Comment by chrisant996** [comment] 2024-10-14 01:01
Aw man. I tried to test all the things thoroughly. I must have missed something specifically about the zip update mechanism. 

I'll look into it tonight.

You can try installing with the setup.exe program and that should work.

**Comment by chrisant996** [comment] 2024-10-14 03:20
Sigh.  The updater has a bug that doesn't support subdirectories under the Clink program directory.  And Clink v1.7.0 now includes a `themes\` subdirectory there.

The updater updated everything _except_ the new `themes\` subdirectory and the *.clinktheme and *.clinkprompt files in it.  Which are the main feature of v1.7.0.

For now, you can go to [the latest release](https://github.com/chrisant996/clink/releases/latest) and manually extract the `themes\` subdirectory from the .zip file there.  Then create a `themes\` subdirectory under Clink's program directory, and copy into it the files from the .zip file's `themes\` subdirectory.

I'll work on solving the updater issue.

**Comment by chrisant996** [comment] 2024-10-14 08:22
Yes.  In testing, it worked.  But in the live update it's still hitting a specific problem that I already fixed during the testing.  I'm investigating, and deleting v1.7.1.

**Comment by chrisant996** [comment] 2024-10-14 08:47
It's working fine with test builds.  But not with release builds.

It deletes the files in a directory, and deletes the directory.
And then in release builds the directory is still present, but in test builds it's properly gone.

It almost seems like it might be a timing issue with antivirus software.

**Comment by chrisant996** [comment] 2024-10-14 09:49
I've added logging and retries.

This is very frustrating for me, because I'm doing detailed and time consuming tests.
It's not like I'm publishing untested changes.

Here comes attempt number 3...  😕

**Comment by atamasco** [comment] 2024-10-14 09:55
Still the same error (Windows 11, admin user):
```
D:\>clink update
Checking latest version...
Downloading latest release v1.7.2...
Expanding zip file...
No such file or directory; failed to install file 'themes\'.
```

**Comment by d4k0** [comment] 2024-10-14 10:00
I can also confirm the same error under Windows 10:

```
clink update
Checking latest version...
Downloading latest release v1.7.2...
Expanding zip file...
No such file or directory; failed to install file 'themes\'.
```

**Comment by chrisant996** [comment] 2024-10-14 10:00
v1.7.2 solves the problem.  _**But you have to update twice:  run `clink update` and it fails to install the themes\ directory, but if you start a new Clink session and run `clink update` again then it's able to install the themes\ directory.

I think maybe v1.7.1 had already solved the problem:  The first update fails; there's no way around that.  Because when updating from version X to version Y, the updater code that's running _is from version X_.  I forgot to explain that two updates are necessary to finish the update.

**Comment by chrisant996** [comment] 2024-10-14 10:01
> v1.7.2 solves the problem. _**But you have to update twice: run `clink update` and it fails to install the themes\ directory, but if you start a new Clink session and run `clink update` again then it's able to install the themes\ directory.
> 
> I think maybe v1.7.1 had already solved the problem: The first update fails; there's no way around that. Because when updating from version X to version Y, the updater code that's running _is from version X_. I forgot to explain that two updates are necessary to finish the update.

You have to start a new Clink session and then it will finish the update.  There's nothing I can do to fix the initial error -- the code for that is already on everyone's machines.

**Comment by d4k0** [comment] 2024-10-14 10:04
Ah, the second run of `clink update` solves the problem, in the notification email from Github the note was not there. Thank you!

**Comment by chrisant996** [comment] 2024-10-14 10:05
# The initial update reports an error.  Start a new Clink session after the error, and it will finish the update successfully.

There's nothing that can be done to prevent the initial error because it's running the updater code that's already on your computer from the older copy of Clink.  I can't even add a clarifying message.  Because the updater code is always from the previous version of Clink -- it's never from the new version.  😓

**Comment by MagicAndre1981** [comment] 2024-10-14 10:06
thanks, second update worked:

```
Microsoft Windows [Version 10.0.22631.4317]
(c) Microsoft Corporation. Alle Rechte vorbehalten.

Clink v1.7.2.f5e99f
Copyright (c) 2012-2018 Martin Ridgers
Portions Copyright (c) 2020-2024 Christopher Antos
https://github.com/chrisant996/clink

Clink v1.7.2 needs to be updated again to install the themes directory.
- To apply the update, run 'clink update'.
- To view the release notes, visit the Releases page:
  https://github.com/chrisant996/clink/releases

C:\Windows\System32>clink update
Checking latest version...
Expanding zip file...
Updating registry keys...

Updated Clink to v1.7.2.

To view the release notes, visit the Releases page:
  https://github.com/chrisant996/clink/releases

C:\Windows\System32>
```

**Comment by atamasco** [comment] 2024-10-14 10:06
Confirmed, runnig the update a 2nd time works. 👍

**Comment by wbpayne22902** [comment] 2024-10-14 14:45
For some reason on my machine, although the update completed the second time successfully, I still cannot use any of the new color themes or prompts.  I have stock settings so it can't be any lua script interfering.

**Comment by chrisant996** [comment] 2024-10-14 16:08
> For some reason on my machine, although the update completed the second time successfully, I still cannot use any of the new color themes or prompts. I have stock settings so it can't be any lua script interfering.

For tracking purposes I've moved that to a new separate issue #682, since it's not related to this issue.

**Comment by chrisant996** [comment] 2024-10-16 03:00
Closing this now, as the issue is fixed and mitigated, and running `clink update` again finishes the update successfully.

**Closed by chrisant996** 2024-10-16 03:00 UTC
Labels: bug

**Comment by plutonium-239** [comment] 2024-10-20 09:14
Hi, I read in the update notes that I had to run it twice, so I had done that and updated to 1.7.3, but unfortunately it wasn't mentioned that I needed to make a new session before the second update. 
Now it has updated to 1.7.3 and there is no `themes/` directory. :(

Also, I tried to manually add `themes/` extracted from the zip to my install location in program files (where `clink.exe` lives), but `clink` doesn't seem to recognize those.

```cmd
14:38:49|C:\Windows\system32>clink config theme use dracula
Theme 'dracula' not found.

14:38:53|C:\Windows\system32>clink config theme list

14:38:56|C:\Windows\system32>
```

**Comment by chrisant996** [comment] 2024-10-20 13:48
Did you manually create a themes directory in between the two updates?

Running `clink update` twice without starting a new session works fine to finish the update. 

But if a themes directory is manually added between the two update commands, then it thinks the themes directory was successfully installed and the second update just says it's already up to date.

Can you try deleting the themes directory and then run `clink update`?

**Comment by chrisant996** [comment] 2024-10-21 16:48
Moved three comments to #692 for tracking purposes because they're a separate issue.
