### ISSUE TITLE
Creating files and directories in the system in portable mode.

### ISSUE THREAD

**Issue by Az-Tart** [chrisant996/clink#554] opened 2024-01-30 10:58 UTC
After create .bat file `Portable.bat`:
```bat
@echo off
rem -- Do any other desired configuration here, such as loading a doskey macro file.
call "%~dp0clink.bat" inject --profile "%~dp0clink_portable" %1 %2 %3 %4 %5 %6 %7 %8 %9
```
clink after launch creates folders `~\AppData\Localc\Temp\clink\dll_cache\1.6.2.864f24_aba916ad` and `~\AppData\Local\Temp\clink\updater\` and empty folder   `~\AppData\Local\clink`.

I use terminal emulator ConEmu.

Clink version 1.6.2
ConEmu version 230724
Windows version 10.0.18363.1316

**Comment by chrisant996** [comment] 2024-01-30 17:50
@Az-Tart it isn't a "mode" per se, and the documentation says it's a way to have a portable profile directory.

The "portable" part means you can "take the profile with you".
It doesn't mean "never write anywhere except the profile directory".

Regarding the three directories:
- `%LOCALAPPDATA%\clink` -- That wasn't intentional, and commit 2f745d2142a16c44e52fca27d4c7e941a763a121 will avoid that starting in v1.6.3.
- `%LOCALAPPDATA%\Temp\clink\updater` -- To prevent the updater from writing to the TEMP directory, run `clink set clink.autoupdate off` to turn off the updater.
- `%LOCALAPPDATA%\Temp\clink\dll_cache\1.6.2.864f24_aba916ad` -- This belongs in the TEMP directory.

Why do you want nothing to be written in the TEMP directory?
What problem is caused by copying a DLL into the TEMP directory?
If you don't want to allow Clink to write to TEMP, then where should it write instead?

**Comment by Az-Tart** [comment] 2024-01-31 07:53
@chrisant996 Thanks for the clarifications.
Because it is my priority that portable programs do not leave anything behind on the system. It would be nice to have temp files saved to the Clink root directory. Is it possible to do this?

**Comment by chrisant996** [comment] 2024-01-31 08:37
The portable.bat script makes the _configuration_ portable.

There was never any intent to make Clink be a "portable program" in the sense you want.

I can add it to the to-do list, and maybe I can investigate the possibility at some point.

**Comment by Az-Tart** [comment] 2024-01-31 09:18
@chrisant996  I understand you. I'm hoping for updates. Thanks.

**Comment by chrisant996** [comment] 2024-01-31 10:35
> It would be nice to have temp files saved to the Clink root directory. Is it possible to do this?

@Az-Tart Some clarifications:

**Re: "Clink root directory" --**
- Neither the Clink binaries directory nor the Clink profile directory would be an ok place to write temp files.
- The only possibility would be a separate configurable location.

**Re: "have temp files saved" --**
- What maximum size temp files would be acceptable in the portable storage?
- What would be expected to happen for files that don't fit?
- How will temp files be purged from the portable storage?  Since it wouldn't be the OS temp directory, there won't be any automatic purging.  Either you would have to purge files yourself, or some kind of temp file manager would have to be created.
- Which temp files do you want diverted into the portable storage?  If you want literally _zero_ temp files in the OS temp directory, not even from Lua scripts that write temp files, and etc, then that's just impossible.

Hopefully these additional statements and questions help illustrate why the request is not simple, and isn't something Clink was trying to accomplish.

For now, I'm going to close this issue, because it isn't a planned work item.  But it will be added to the todo.md file for future consideration.

**Closed by chrisant996** 2024-01-31 10:35 UTC
Labels: enhancement

**Comment by chrisant996** [comment] 2024-07-28 22:35
This is being removed from the wish list because:

I use multiple "portable programs", and all of them use the system TEMP directory for various things.  The program and its configuration are portable, but that doesn't mean it exists in a bubble isolated from core OS services.

I won't try to build some kind of way for Clink to avoid using the TEMP directory for temporary files, especially since scripts and programs launched by Clink would still use the system TEMP directory.

I understand the request, but it's inconsistent with the purpose of the TEMP directory, and isn't feasible to the degree that was requested.
