### ISSUE TITLE
clink-popup-* windows are unnecessarily narrow and truncate the search text when opened with an initial search

### ISSUE THREAD

**Issue by kahlkevin** [chrisant996/clink#579] opened 2024-03-23 08:01 UTC
|||
|-|-|
|**Tested Version**| Clink v1.6.9.242b68 (although this repros with earlier versions)|
|**Tested Commands**|`clink-popup-history`, `clink-popup-directories`

## Repro

1. Navigate to some long directory path (like, say, 25-50 characters long) -- or -- Create a long-ish command history entry
2. Type a couple or few characters that you know are present in the history entry created in step 1 
3. Activate `clink-popup-directories` or `clink-popup-history`

## Result

Popup window appears but is rather narrow. Text is unnecessarily truncated within view.

## Expect

A much wider popup window.

## Note

This does not repro if you skip step 2 (no search filter). The resulting popup is much wider and avoids truncation.

**Comment by chrisant996** [comment] 2024-03-23 17:47
I can't reproduce the issue.

![image](https://github.com/chrisant996/clink/assets/17440311/745fef66-2181-4183-a9f6-61c9b3403ab7)

Can you share a screenshot?
Can you narrow down more specific steps?

**Comment by chrisant996** [comment] 2024-03-23 17:56
@kahlkevin Ah, but this part I can repro:

![image](https://github.com/chrisant996/clink/assets/17440311/930b968a-4a73-42ff-99db-9965f54a964a)

Debugging...

**Comment by chrisant996** [comment] 2024-03-23 18:22
@kahlkevin The same truncation could happen in the history popup list, if timestamps are not shown (thus it would accidentally reserve room for 2 columns even though there's only 1 column).

![image](https://github.com/chrisant996/clink/assets/17440311/92ec1769-2649-461d-819c-5834cba4a98b)

But I don't see any way for the window width to be too narrow:  the window width is the length of the longest entry, or the width of the screen, whichever is smaller.

Could it have been an optical illusion that the window was overly narrow?

**Comment by chrisant996** [comment] 2024-03-23 18:50
@kahlkevin I'm pretty sure the window width is correct, and that only the text within the window was truncated unnecessarily.  I'll close this issue for now, but please double check and report back if the window width itself is wrong.

**Closed by chrisant996** 2024-03-23 18:50 UTC
Labels: bug, needs more information

**Comment by kahlkevin** [comment] 2024-03-25 01:34
Yep, I agree that it's possible I was commenting upon an optical illusion (w.r.t. the overall window width) and am completely supportive of your issue title change.

**However**: unfortunately, this still repros for me with 1.6.10...

**Comment by chrisant996** [comment] 2024-03-25 02:24
> Yep, I agree that it's possible I was commenting upon an optical illusion (w.r.t. the overall window width) and am completely supportive of your issue title change.
> 
> **However**: unfortunately, this still repros for me with 1.6.10...

Interesting! Can you share more information?

- screen shot
- more specific details about steps
- output from `clink info`
- contents of the `clink.log` (its location is listed in the output from `clink info`).

**Comment by kahlkevin** [comment] 2024-03-25 03:27
- Screenshot sent via private message (using the email address displayed in your GitHub profile).

- `clink info` yields:
```
version  : 1.6.10.d5dce0
session  : 20168
injected : C:\Users\kkahl\AppData\Local\Temp\clink\dll_cache\1.6.9.242b68_70f2e7d0\clink_dll_x64.dll (1.6.9)
binaries : C:\util\clink
state    : C:\Users\kkahl\AppData\Local\clink
log      : C:\Users\kkahl\AppData\Local\clink\clink.log
settings : C:\Users\kkahl\AppData\Local\clink\clink_settings
history  : C:\Users\kkahl\AppData\Local\clink\clink_history
scripts  : C:\util\clink ; C:\Users\kkahl\AppData\Local\clink ; C:\Users\kkahl\clink-completions
inputrc  : %clink_inputrc%
             (unset)
         : state directory
             C:\Users\kkahl\AppData\Local\clink\.inputrc
             C:\Users\kkahl\AppData\Local\clink\_inputrc
         : %userprofile%
             C:\Users\kkahl\.inputrc   (LOAD)
             C:\Users\kkahl\_inputrc
         : %localappdata%
             C:\Users\kkahl\AppData\Local\.inputrc
             C:\Users\kkahl\AppData\Local\_inputrc
         : %appdata%
             C:\Users\kkahl\AppData\Roaming\.inputrc
             C:\Users\kkahl\AppData\Roaming\_inputrc
         : %home%
             C:\Users\kkahl\.inputrc   (exists)
             C:\Users\kkahl\_inputrc
system   : 10.0.26085.1
codepage : 1252
keyboard langid : 1033
keyboard layout : 00000409
```
- [clink.log](https://github.com/chrisant996/clink/files/14738437/clink.log) attached

**Comment by kahlkevin** [comment] 2024-03-25 04:29
Ah, nevermind, now I see the problem: the old version of `clink_dll_x64.dll` was still in use. After closing and re-opening the shell command prompt, the issue is fixed.

Thanks!

**Comment by chrisant996** [comment] 2024-03-25 07:03
> Ah, nevermind. False alarm. Now I see the problem: the old version of `clink_dll_x64.dll` was still in use. After closing and re-opening the shell command prompt, the issue is fixed.

Ah, that's good news.  Thanks for returning the issues, and thanks for the update!
